/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V2.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;
    /// <summary>
    /// Represents arguments for NFS v2 create operations.
    /// </summary>
    public class CreateArguments : XdrAble
    {
        private ItemOperationArguments _Where;
        private CreateAttributes _Attributes;

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateArguments"/> class.
        /// </summary>
        public CreateArguments()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateArguments"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public CreateArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._Where.XdrEncode(xdr);
            this._Attributes.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Where = new ItemOperationArguments(xdr);
            this._Attributes = new CreateAttributes(xdr);
        }

        /// <summary>
        /// Gets or sets the location where the item should be created.
        /// </summary>
        public ItemOperationArguments Where
        {
            get
            { return this._Where; }
            set
            { this._Where = value; }
        }

        /// <summary>
        /// Gets or sets the attributes for the item to be created.
        /// </summary>
        public CreateAttributes Attributes
        {
            get
            { return this._Attributes; }
            set
            { this._Attributes = value; }
        }
    }
}