/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V2.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;
    /// <summary>
    /// Represents a directory entry in NFS v2 protocol directory listings.
    /// </summary>
    public class Entry : XdrAble
    {
        private int _FileId; /* fileid is not long on on NFSV1&NFSV2. this value is long NFSV3 and later... */
        private Name _Name;
        private NFSCookie _Cookie;
        private Entry _NextEntry;

        /// <summary>
        /// Initializes a new instance of the <see cref="Entry"/> class.
        /// </summary>
        public Entry()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="Entry"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public Entry(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Entry _this = this;

            do
            {
                xdr.XdrEncodeInt(_this._FileId);

                _this._Name.XdrEncode(xdr);
                _this._Cookie.XdrEncode(xdr);
                _this = _this._NextEntry;

                xdr.XdrEncodeBoolean(_this != null);
            } while (_this != null);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Entry _this = this;
            Entry _next;

            do
            {
                _this._FileId = xdr.XdrDecodeInt();
                _this._Name = new Name(xdr);
                _this._Cookie = new NFSCookie(xdr);
                _next = xdr.XdrDecodeBoolean() ? new Entry() : null;
                _this._NextEntry = _next;
                _this = _next;
            } while (_this != null);
        }

        /// <summary>
        /// Gets the file ID of the directory entry.
        /// </summary>
        public int FileID
        {
            get
            { return this._FileId; }
        }

        /// <summary>
        /// Gets the name of the directory entry.
        /// </summary>
        public Name Name
        {
            get
            { return this._Name; }
        }

        /// <summary>
        /// Gets the cookie value for directory listing pagination.
        /// </summary>
        public NFSCookie Cookie
        {
            get
            { return this._Cookie; }
        }

        /// <summary>
        /// Gets the next entry in the directory listing chain.
        /// </summary>
        public Entry NextEntry
        {
            get
            { return this._NextEntry; }
        }
    }

    // End of entry.cs
}