/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V2.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;
    /// <summary>
    /// Represents arguments for NFS v2 file attribute operations.
    /// </summary>
    public class FileArguments : XdrAble
    {
        private NFSHandle _File;
        private CreateAttributes _Attributes;

        /// <summary>
        /// Initializes a new instance of the <see cref="FileArguments"/> class.
        /// </summary>
        public FileArguments()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileArguments"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public FileArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._File.XdrEncode(xdr);
            this._Attributes.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._File = new NFSHandle();
            this._File.Version = V2.RPC.NFSv2Protocol.NFS_VERSION;
            this._File.XdrDecode(xdr);
            this._Attributes = new CreateAttributes(xdr);
        }

        /// <summary>
        /// Gets or sets the file handle.
        /// </summary>
        public NFSHandle File
        {
            get
            { return this._File; }
            set
            { this._File = value; }
        }

        /// <summary>
        /// Gets or sets the file attributes.
        /// </summary>
        public CreateAttributes Attributes
        {
            get
            { return this._Attributes; }
            set
            { this._Attributes = value; }
        }
    }

    // End of sattrargs.cs
}