/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V2.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;
    /// <summary>
    /// Represents arguments for NFS v2 item operations with directory handle and name.
    /// </summary>
    public class ItemOperationArguments : XdrAble
    {
        private NFSHandle _Dir;
        private Name _Name;

        /// <summary>
        /// Initializes a new instance of the <see cref="ItemOperationArguments"/> class.
        /// </summary>
        public ItemOperationArguments()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ItemOperationArguments"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public ItemOperationArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._Dir.XdrEncode(xdr);
            this._Name.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Dir = new NFSHandle();
            this._Dir.Version = V2.RPC.NFSv2Protocol.NFS_VERSION;
            this._Dir.XdrDecode(xdr);
            this._Name = new Name(xdr);
        }

        /// <summary>
        /// Gets or sets the directory handle.
        /// </summary>
        public NFSHandle Directory
        {
            get
            { return this._Dir; }
            set
            { this._Dir = value; }
        }

        /// <summary>
        /// Gets or sets the item name.
        /// </summary>
        public Name Name
        {
            get
            { return this._Name; }
            set
            { this._Name = value; }
        }
    }

    // End of diropargs.cs
}