/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V2.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;
    /// <summary>
    /// Represents arguments for NFS v2 directory read operations.
    /// </summary>
    public class ItemArguments : XdrAble
    {
        private NFSHandle _Item;
        private NFSCookie _Cookie;
        private int _Count;

        /// <summary>
        /// Initializes a new instance of the <see cref="ItemArguments"/> class.
        /// </summary>
        public ItemArguments()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ItemArguments"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public ItemArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._Item.XdrEncode(xdr);
            this._Cookie.XdrEncode(xdr);
            xdr.XdrEncodeInt(this._Count);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Item = new NFSHandle();
            this._Item.Version = V2.RPC.NFSv2Protocol.NFS_VERSION;
            this._Item.XdrDecode(xdr);
            this._Cookie = new NFSCookie(xdr);
            this._Count = xdr.XdrDecodeInt();
        }

        /// <summary>
        /// Gets or sets the directory handle.
        /// </summary>
        public NFSHandle HandleObject
        {
            get
            { return this._Item; }
            set
            { this._Item = value; }
        }

        /// <summary>
        /// Gets or sets the cookie for directory listing continuation.
        /// </summary>
        public NFSCookie Cookie
        {
            get
            { return this._Cookie; }
            set
            { this._Cookie = value; }
        }

        /// <summary>
        /// Gets or sets the maximum number of entries to return.
        /// </summary>
        public int Count
        {
            get
            { return this._Count; }
            set
            { this._Count = value; }
        }
    }

    // End of readdirargs.cs
}