/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V2.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;
    /// <summary>
    /// Represents the status response for NFS v2 read operations.
    /// </summary>
    public class ReadStatus : XdrAble
    {
        private NFSStats _Status;
        private ReadAccessOK _Ok;

        /// <summary>
        /// Initializes a new instance of the <see cref="ReadStatus"/> class.
        /// </summary>
        public ReadStatus()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReadStatus"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public ReadStatus(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt((int)this._Status);

            switch (this._Status)
            {
                case NFSStats.NFS_OK:
                    this._Ok.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Status = (NFSStats)xdr.XdrDecodeInt();
            switch (this._Status)
            {
                case NFSStats.NFS_OK:
                    this._Ok = new ReadAccessOK(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Gets the operation status code.
        /// </summary>
        public NFSStats Status
        {
            get
            { return this._Status; }
        }

        /// <summary>
        /// Gets the read result (available when status is NFS_OK).
        /// </summary>
        public ReadAccessOK OK
        {
            get
            { return this._Ok; }
        }
    }
}