/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V2.RPC.Mount
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;
    /// <summary>
    /// Represents the result of an NFS v2 mount operation.
    /// </summary>
    public class MountStatus : XdrAble
    {
        private NFSMountStats _Status;
        private NFSHandle _Handle;

        /// <summary>
        /// Initializes a new instance of the <see cref="MountStatus"/> class.
        /// </summary>
        public MountStatus()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="MountStatus"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public MountStatus(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt((int)this._Status);

            switch (this._Status)
            {
                case NFSMountStats.MNT_OK:
                    this._Handle.Version = V2.RPC.NFSv2Protocol.NFS_VERSION;
                    this._Handle.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Status = (NFSMountStats)xdr.XdrDecodeInt();

            switch (this._Status)
            {
                case NFSMountStats.MNT_OK:
                    this._Handle = new NFSHandle();
                    this._Handle.Version = V2.RPC.NFSv2Protocol.NFS_VERSION;
                    this._Handle.XdrDecode(xdr);

                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Gets the file handle returned by the mount operation.
        /// </summary>
        public NFSHandle Handle
        {
            get
            { return this._Handle; }
        }

        /// <summary>
        /// Gets the mount operation status.
        /// </summary>
        public NFSMountStats Status
        {
            get
            { return this._Status; }
        }
    }

    // End of fhstatus.cs
}