/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V2.RPC.Mount
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;
    using System.Net;

    /// <summary>
    /// Represents the client stub proxy for the NFS v2 mount protocol operations.
    /// </summary>
    public class NFSv2MountProtocolClient : OncRpcClientStub
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv2MountProtocolClient"/> class.
        /// </summary>
        /// <param name="host">The host address of the mount server.</param>
        /// <param name="protocol">The ONC/RPC protocol to use.</param>
        public NFSv2MountProtocolClient(IPAddress host, int protocol)
            : base(host, NFSv2MountProtocol.MOUNTPROG, 1, 0, protocol, true)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv2MountProtocolClient"/> class.
        /// </summary>
        /// <param name="host">The host address of the mount server.</param>
        /// <param name="protocol">The ONC/RPC protocol to use.</param>
        /// <param name="useSecurePort">Whether to use a secure port.</param>
        public NFSv2MountProtocolClient(IPAddress host, int protocol, bool useSecurePort)
            : base(host, NFSv2MountProtocol.MOUNTPROG, 1, 0, protocol, useSecurePort)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv2MountProtocolClient"/> class.
        /// </summary>
        /// <param name="host">The host address of the mount server.</param>
        /// <param name="port">The port number.</param>
        /// <param name="protocol">The ONC/RPC protocol to use.</param>
        public NFSv2MountProtocolClient(IPAddress host, int port, int protocol)
            : base(host, NFSv2MountProtocol.MOUNTPROG, 1, port, protocol, true)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv2MountProtocolClient"/> class.
        /// </summary>
        /// <param name="client">The ONC/RPC client connection object.</param>
        public NFSv2MountProtocolClient(OncRpcClient client)
            : base(client)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv2MountProtocolClient"/> class.
        /// </summary>
        /// <param name="host">The host address of the mount server.</param>
        /// <param name="program">The remote program number.</param>
        /// <param name="version">The remote program version number.</param>
        /// <param name="protocol">The ONC/RPC protocol to use.</param>
        public NFSv2MountProtocolClient(IPAddress host, int program, int version, int protocol)
            : base(host, program, version, 0, protocol, true)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv2MountProtocolClient"/> class.
        /// </summary>
        /// <param name="host">The host address of the mount server.</param>
        /// <param name="program">The remote program number.</param>
        /// <param name="version">The remote program version number.</param>
        /// <param name="port">The port number.</param>
        /// <param name="protocol">The ONC/RPC protocol to use.</param>
        public NFSv2MountProtocolClient(IPAddress host, int program, int version, int port, int protocol)
            : base(host, program, version, port, protocol, true)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv2MountProtocolClient"/> class.
        /// </summary>
        /// <param name="host">The host address of the mount server.</param>
        /// <param name="program">The remote program number.</param>
        /// <param name="version">The remote program version number.</param>
        /// <param name="port">The port number.</param>
        /// <param name="protocol">The ONC/RPC protocol to use.</param>
        /// <param name="useSecurePort">Whether to use a secure port.</param>
        public NFSv2MountProtocolClient(IPAddress host, int program, int version, int port, int protocol, bool useSecurePort)
            : base(host, program, version, port, protocol, useSecurePort)
        {
        }

        /// <summary>
        /// Calls the remote MOUNTPROC_NULL procedure to test server availability.
        /// </summary>
        public void MOUNTPROC_NULL()
        {
            XdrVoid args_ = XdrVoid.XDR_VOID;
            XdrVoid result_ = XdrVoid.XDR_VOID;

            client.call(NFSv2MountProtocol.MOUNTPROC_NULL, NFSv2MountProtocol.MOUNTVERS, args_, result_);
        }

        /// <summary>
        /// Calls the remote MOUNTPROC_MNT procedure to mount a file system.
        /// </summary>
        /// <param name="arg1">The directory path to mount.</param>
        /// <returns>The mount status result containing the file handle.</returns>
        public MountStatus MOUNTPROC_MNT(Name arg1)
        {
            MountStatus result_ = new MountStatus();

            client.call(NFSv2MountProtocol.MOUNTPROC_MNT, NFSv2MountProtocol.MOUNTVERS, arg1, result_);

            return result_;
        }

        /// <summary>
        /// Calls the remote MOUNTPROC_DUMP procedure to retrieve the list of mounted file systems.
        /// </summary>
        /// <returns>The mount list result.</returns>
        public MountList MOUNTPROC_DUMP()
        {
            XdrVoid args_ = XdrVoid.XDR_VOID;
            MountList result_ = new MountList();

            client.call(NFSv2MountProtocol.MOUNTPROC_DUMP, NFSv2MountProtocol.MOUNTVERS, args_, result_);

            return result_;
        }

        /// <summary>
        /// Calls the remote MOUNTPROC_UMNT procedure to unmount a file system.
        /// </summary>
        /// <param name="arg1">The directory path to unmount.</param>
        public void MOUNTPROC_UMNT(Name arg1)
        {
            XdrVoid result_ = XdrVoid.XDR_VOID;

            client.call(NFSv2MountProtocol.MOUNTPROC_UMNT, NFSv2MountProtocol.MOUNTVERS, arg1, result_);
        }

        /// <summary>
        /// Calls the remote MOUNTPROC_UMNTALL procedure to unmount all file systems.
        /// </summary>
        public void MOUNTPROC_UMNTALL()
        {
            XdrVoid args_ = XdrVoid.XDR_VOID;
            XdrVoid result_ = XdrVoid.XDR_VOID;

            client.call(NFSv2MountProtocol.MOUNTPROC_UMNTALL, NFSv2MountProtocol.MOUNTVERS, args_, result_);
        }

        /// <summary>
        /// Calls the remote MOUNTPROC_EXPORT procedure to retrieve the export list.
        /// </summary>
        /// <returns>The exports result containing available exports.</returns>
        public Exports MOUNTPROC_EXPORT()
        {
            XdrVoid args_ = XdrVoid.XDR_VOID;
            Exports result_ = new Exports();

            client.call(NFSv2MountProtocol.MOUNTPROC_EXPORT, NFSv2MountProtocol.MOUNTVERS, args_, result_);

            return result_;
        }
    }

    // End of NFSv2MountProtocolClient.cs
}