/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of the ACCESS operation in NFSv4.
    /// </summary>
    public class Access4Res : XdrAble
    {
        /// <summary>
        /// Gets or sets the operation status code.
        /// </summary>
        public int Status;

        /// <summary>
        /// Gets or sets the successful result data (only valid when status is NFS4_OK).
        /// </summary>
        public Access4Resok Resok4;

        /// <summary>
        /// Initializes a new instance of the <see cref="Access4Res"/> class.
        /// </summary>
        public Access4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Access4Res"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Access4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Status);
            switch (Status)
            {
                case Nfsstat4.NFS4_OK:
                    Resok4.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Status = xdr.XdrDecodeInt();
            switch (Status)
            {
                case Nfsstat4.NFS4_OK:
                    Resok4 = new Access4Resok(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
