/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents ACE (Access Control Entry) mask for NFSv4 access control.
    /// </summary>
    public class Acemask4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the ACE mask value.
        /// </summary>
        public int Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Acemask4"/> class.
        /// </summary>
        public Acemask4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Acemask4"/> class with a specific value.
        /// </summary>
        /// <param name="value">The ACE mask value.</param>
        public Acemask4(int value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Acemask4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Acemask4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Value);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeInt();
        }
    }
}
