/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents an attribute list for NFSv4 file attributes.
    /// </summary>
    public class Attrlist4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the encoded attribute list data.
        /// </summary>
        public byte[] Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Attrlist4"/> class.
        /// </summary>
        public Attrlist4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Attrlist4"/> class with specific data.
        /// </summary>
        /// <param name="value">The encoded attribute list data.</param>
        public Attrlist4(byte[] value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Attrlist4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Attrlist4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeDynamicOpaque(Value);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeDynamicOpaque();
        }
    }
}
