/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the BACKCHANNEL_CTL operation in NFSv4.
    /// </summary>
    public class BackchannelCtl4Args : XdrAble
    {
        /// <summary>
        /// Gets or sets the callback program number.
        /// </summary>
        public int Bca_cb_program;

        /// <summary>
        /// Gets or sets the security parameters for the backchannel.
        /// </summary>
        public CallbackSecParms4[] Bca_sec_parms;

        /// <summary>
        /// Initializes a new instance of the <see cref="BackchannelCtl4Args"/> class.
        /// </summary>
        public BackchannelCtl4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BackchannelCtl4Args"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public BackchannelCtl4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            { int size = Bca_sec_parms.Length; xdr.XdrEncodeInt(size); for (int idx = 0; idx < size; ++idx) { Bca_sec_parms[idx].XdrEncode(xdr); } }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            { int size = xdr.XdrDecodeInt(); Bca_sec_parms = new CallbackSecParms4[size]; for (int idx = 0; idx < size; ++idx) { Bca_sec_parms[idx] = new CallbackSecParms4(xdr); } }
        }
    }
}
