/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result data for the BIND_CONN_TO_SESSION operation in NFSv4.
    /// </summary>
    public class BindConnToSession4Resok : XdrAble
    {
        /// <summary>
        /// Gets or sets the session ID.
        /// </summary>
        public Sessionid4 Bctsr_sessid;

        /// <summary>
        /// Gets or sets the channel direction.
        /// </summary>
        public int Bctsr_dir;

        /// <summary>
        /// Gets or sets a value indicating whether the connection is using RDMA mode.
        /// </summary>
        public bool Bctsr_use_conn_in_rdma_mode;

        /// <summary>
        /// Initializes a new instance of the <see cref="BindConnToSession4Resok"/> class.
        /// </summary>
        public BindConnToSession4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BindConnToSession4Resok"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public BindConnToSession4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Bctsr_dir);
            xdr.XdrEncodeBoolean(Bctsr_use_conn_in_rdma_mode);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Bctsr_dir = xdr.XdrDecodeInt();
            Bctsr_use_conn_in_rdma_mode = xdr.XdrDecodeBoolean();
        }
    }
}
