/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a bitmap for NFSv4 attribute masks.
    /// </summary>
    public class Bitmap4 : XdrAble
    {
        /// <summary>
        /// An array of 32-bit unsigned integers representing attribute bitmaps. Each bit position
        /// corresponds to a specific NFSv4 file attribute (e.g., size, mode, owner). The bitmap
        /// can extend across multiple words to support all defined attributes. Bit 0 of Value[0]
        /// is the lowest attribute, bit 31 of Value[0] is attribute 31, bit 0 of Value[1] is
        /// attribute 32, and so on.
        /// </summary>
        public Uint32T[] Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Bitmap4"/> class.
        /// </summary>
        public Bitmap4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Bitmap4"/> class with specific values.
        /// </summary>
        /// <param name="value">The bitmap values array.</param>
        public Bitmap4(Uint32T[] value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Bitmap4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Bitmap4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            int size = Value.Length;
            xdr.XdrEncodeInt(size);
            for (int idx = 0; idx < size; ++idx)
            {
                Value[idx].XdrEncode(xdr);
            }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            int size = xdr.XdrDecodeInt();
            Value = new Uint32T[size];
            for (int idx = 0; idx < size; ++idx)
            {
                Value[idx] = new Uint32T(xdr);
            }
        }
    }
}
