/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /// <summary>
    /// Defines channel direction constants from the server perspective for NFSv4.1.
    /// </summary>
    public class ChannelDirFromServer4
    {
        /// <summary>
        /// Cdfs4 Fore.
        /// </summary>
        public const int CDFS4_FORE = 0x1;
        /// <summary>
        /// Cdfs4 Back.
        /// </summary>
        public const int CDFS4_BACK = 0x2;
        /// <summary>
        /// Cdfs4 Both.
        /// </summary>
        public const int CDFS4_BOTH = 0x3;
    }
}
