/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents change information for NFSv4 operations, including before and after change identifiers.
    /// </summary>
    public class ChangeInfo4 : XdrAble
    {
        /// <summary>
        /// Gets or sets a value indicating whether the operation was atomic.
        /// </summary>
        public bool Atomic;

        /// <summary>
        /// Gets or sets the change ID before the operation.
        /// </summary>
        public Changeid4 Before;

        /// <summary>
        /// Gets or sets the change ID after the operation.
        /// </summary>
        public Changeid4 After;

        /// <summary>
        /// Initializes a new instance of the <see cref="ChangeInfo4"/> class.
        /// </summary>
        public ChangeInfo4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChangeInfo4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public ChangeInfo4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeBoolean(Atomic);
            Before.XdrEncode(xdr);
            After.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Atomic = xdr.XdrDecodeBoolean();
            Before = new Changeid4(xdr);
            After = new Changeid4(xdr);
        }
    }
}
