/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents client owner information for NFSv4 client identification.
    /// </summary>
    public class ClientOwner4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the co verifier.
        /// </summary>
        public Verifier4 Co_verifier;
        /// <summary>
        /// Gets or sets the co ownerid.
        /// </summary>
        public byte[] Co_ownerid;

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientOwner4"/> class.
        /// </summary>
        public ClientOwner4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ClientOwner4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public ClientOwner4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Co_verifier.XdrEncode(xdr);
            xdr.XdrEncodeDynamicOpaque(Co_ownerid);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Co_verifier = new Verifier4(xdr);
            Co_ownerid = xdr.XdrDecodeDynamicOpaque();
        }
    }
}
