/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the COMMIT operation in NFSv4.
    /// </summary>
    public class Commit4Args : XdrAble
    {
        /// <summary>
        /// Gets or sets the offset.
        /// </summary>
        public Offset4 Offset;
        /// <summary>
        /// Gets or sets the count.
        /// </summary>
        public Count4 Count;

        /// <summary>
        /// Initializes a new instance of the <see cref="Commit4Args"/> class.
        /// </summary>
        public Commit4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Commit4Args"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Commit4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Count.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Count = new Count4(xdr);
        }
    }
}
