/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the type and associated data for NFSv4 file creation operations.
    /// </summary>
    public class Createtype4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the Type.
        /// </summary>
        public int Type;
        /// <summary>
        /// Gets or sets the Linkdata.
        /// </summary>
        public Linktext4 Linkdata;
        /// <summary>
        /// Gets or sets the Devdata.
        /// </summary>
        public Specdata4 Devdata;

        /// <summary>
        /// Initializes a new instance of the <see cref="Createtype4"/> class.
        /// </summary>
        public Createtype4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Createtype4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Createtype4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Type);
            switch (Type)
            {
                case NfsFtype4.NF4LNK:
                    Linkdata.XdrEncode(xdr);
                    break;

                case NfsFtype4.NF4BLK:
                case NfsFtype4.NF4CHR:
                    Devdata.XdrEncode(xdr);
                    break;

                case NfsFtype4.NF4SOCK:
                case NfsFtype4.NF4FIFO:
                case NfsFtype4.NF4DIR:
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Type = xdr.XdrDecodeInt();
            switch (Type)
            {
                case NfsFtype4.NF4LNK:
                    Linkdata = new Linktext4(xdr);
                    break;

                case NfsFtype4.NF4BLK:
                case NfsFtype4.NF4CHR:
                    Devdata = new Specdata4(xdr);
                    break;

                case NfsFtype4.NF4SOCK:
                case NfsFtype4.NF4FIFO:
                case NfsFtype4.NF4DIR:
                    break;

                default:
                    break;
            }
        }
    }
}
