/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /// <summary>
    /// Defines file creation mode constants for NFSv4 CREATE operations.
    /// </summary>
    public class Createmode4
    {
        /// <summary>
        /// Create file without checking for existence; overwrite if exists.
        /// </summary>
        public const int UNCHECKED4 = 0;
        /// <summary>
        /// Create file only if it does not exist; fail if it exists.
        /// </summary>
        public const int GUARDED4 = 1;
        /// <summary>
        /// Create file exclusively using a verifier.
        /// </summary>
        public const int EXCLUSIVE4 = 2;
        /// <summary>
        /// Create file exclusively with attributes (NFSv4.1).
        /// </summary>
        public const int EXCLUSIVE4_1 = 3;
    }
}
