/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents how a file should be created in NFSv4, including mode and attributes.
    /// </summary>
    public class Createhow4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the Mode.
        /// </summary>
        public int Mode;
        /// <summary>
        /// Gets or sets the Createattrs.
        /// </summary>
        public Fattr4 Createattrs;
        /// <summary>
        /// Gets or sets the Createverf.
        /// </summary>
        public Verifier4 Createverf;
        /// <summary>
        /// Gets or sets the ch createboth.
        /// </summary>
        public Creatverfattr Ch_createboth;

        /// <summary>
        /// Initializes a new instance of the <see cref="Createhow4"/> class.
        /// </summary>
        public Createhow4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Createhow4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Createhow4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Mode);
            switch (Mode)
            {
                case Createmode4.UNCHECKED4:
                case Createmode4.GUARDED4:
                    Createattrs.XdrEncode(xdr);
                    break;

                case Createmode4.EXCLUSIVE4:
                    Createverf.XdrEncode(xdr);
                    break;

                case Createmode4.EXCLUSIVE4_1:
                    Ch_createboth.XdrEncode(xdr);
                    break;
            }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Mode = xdr.XdrDecodeInt();
            switch (Mode)
            {
                case Createmode4.UNCHECKED4:
                case Createmode4.GUARDED4:
                    Createattrs = new Fattr4(xdr);
                    break;

                case Createmode4.EXCLUSIVE4:
                    Createverf = new Verifier4(xdr);
                    break;

                case Createmode4.EXCLUSIVE4_1:
                    Ch_createboth = new Creatverfattr(xdr);
                    break;
            }
        }
    }
}
