/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result data for the CREATE_SESSION operation in NFSv4.
    /// </summary>
    public class CreateSession4Resok : XdrAble
    {
        /// <summary>
        /// Gets or sets the csr sessionid.
        /// </summary>
        public Sessionid4 Csr_sessionid;
        /// <summary>
        /// Gets or sets the csr sequence.
        /// </summary>
        public Sequenceid4 Csr_sequence;
        /// <summary>
        /// Gets or sets the csr flags.
        /// </summary>
        public Uint32T Csr_flags;
        /// <summary>
        /// Gets or sets the csr fore chan attrs.
        /// </summary>
        public ChannelAttrs4 Csr_fore_chan_attrs;
        /// <summary>
        /// Gets or sets the csr back chan attrs.
        /// </summary>
        public ChannelAttrs4 Csr_back_chan_attrs;

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSession4Resok"/> class.
        /// </summary>
        public CreateSession4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSession4Resok"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public CreateSession4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Csr_sessionid.XdrEncode(xdr);
            Csr_sequence.XdrEncode(xdr);
            Csr_flags.XdrEncode(xdr);
            Csr_fore_chan_attrs.XdrEncode(xdr);
            Csr_back_chan_attrs.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Csr_sessionid = new Sessionid4(xdr);
            Csr_sequence = new Sequenceid4(xdr);
            Csr_flags = new Uint32T(xdr);
            Csr_fore_chan_attrs = new ChannelAttrs4(xdr);
            Csr_back_chan_attrs = new ChannelAttrs4(xdr);
        }
    }
}
