/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents creation verifier and attributes for exclusive file creation in NFSv4.
    /// </summary>
    public class Creatverfattr : XdrAble
    {
        /// <summary>
        /// Gets or sets the cva verf.
        /// </summary>
        public Verifier4 Cva_verf;
        /// <summary>
        /// Gets or sets the cva attrs.
        /// </summary>
        public Fattr4 Cva_attrs;

        /// <summary>
        /// Initializes a new instance of the <see cref="Creatverfattr"/> class.
        /// </summary>
        public Creatverfattr()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Creatverfattr"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Creatverfattr(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Cva_verf.XdrEncode(xdr);
            Cva_attrs.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Cva_verf = new Verifier4(xdr);
            Cva_attrs = new Fattr4(xdr);
        }
    }
}
