/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a delegation claim for NFSv4 file delegations.
    /// </summary>
    public class DelegClaim4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the dc claim.
        /// </summary>
        public int Dc_claim;
        /// <summary>
        /// Gets or sets the dc delegate type.
        /// </summary>
        public int Dc_delegate_type;

        /// <summary>
        /// Initializes a new instance of the <see cref="DelegClaim4"/> class.
        /// </summary>
        public DelegClaim4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DelegClaim4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public DelegClaim4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Dc_claim);
            switch (Dc_claim)
            {
                case OpenClaimType4.CLAIM_FH:
                    break;

                case OpenClaimType4.CLAIM_DELEG_PREV_FH:
                    break;

                case OpenClaimType4.CLAIM_PREVIOUS:
                    xdr.XdrEncodeInt(Dc_delegate_type);
                    break;
            }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Dc_claim = xdr.XdrDecodeInt();
            switch (Dc_claim)
            {
                case OpenClaimType4.CLAIM_FH:
                    break;

                case OpenClaimType4.CLAIM_DELEG_PREV_FH:
                    break;

                case OpenClaimType4.CLAIM_PREVIOUS:
                    Dc_delegate_type = xdr.XdrDecodeInt();
                    break;
            }
        }
    }
}
