/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the DELEGRETURN operation in NFSv4.
    /// </summary>
    public class Delegreturn4Args : XdrAble
    {
        /// <summary>
        /// Gets or sets the deleg stateid.
        /// </summary>
        public Stateid4 Deleg_stateid;

        /// <summary>
        /// Initializes a new instance of the <see cref="Delegreturn4Args"/> class.
        /// </summary>
        public Delegreturn4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Delegreturn4Args"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Delegreturn4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
