/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result for the DESTROY_SESSION operation in NFSv4.
    /// </summary>
    public class DestroySession4Res : XdrAble
    {
        /// <summary>
        /// Gets or sets the dsr status.
        /// </summary>
        public int Dsr_status;

        /// <summary>
        /// Initializes a new instance of the <see cref="DestroySession4Res"/> class.
        /// </summary>
        public DestroySession4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DestroySession4Res"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public DestroySession4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
