/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the DESTROY_SESSION operation in NFSv4.
    /// </summary>
    public class DestroySession4Args : XdrAble
    {
        /// <summary>
        /// Gets or sets the dsa sessionid.
        /// </summary>
        public Sessionid4 Dsa_sessionid;

        /// <summary>
        /// Initializes a new instance of the <see cref="DestroySession4Args"/> class.
        /// </summary>
        public DestroySession4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DestroySession4Args"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public DestroySession4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Dsa_sessionid.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Dsa_sessionid = new Sessionid4(xdr);
        }
    }
}
