/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a device identifier for NFSv4.1 pNFS (parallel NFS) operations.
    /// </summary>
    public class Deviceid4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        public byte[] Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Deviceid4"/> class.
        /// </summary>
        public Deviceid4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Deviceid4"/> class with a specific value.
        /// </summary>
        /// <param name="value">The value.</param>
        public Deviceid4(byte[] value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Deviceid4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Deviceid4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeOpaque(Value, NFSv4Protocol.NFS4_DEVICEID4_SIZE);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeOpaque(NFSv4Protocol.NFS4_DEVICEID4_SIZE);
        }
    }
}
