/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a directory entry in NFSv4 directory listings.
    /// </summary>
    public class Entry4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the cookie.
        /// </summary>
        public NfsCookie4 Cookie;
        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        public Component4 Name;
        /// <summary>
        /// Gets or sets the attrs.
        /// </summary>
        public Fattr4 Attrs;
        /// <summary>
        /// Gets or sets the nextentry.
        /// </summary>
        public Entry4 Nextentry;

        /// <summary>
        /// Initializes a new instance of the <see cref="Entry4"/> class.
        /// </summary>
        public Entry4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Entry4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Entry4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Entry4 current = this;
            do
            {
                current.Cookie.XdrEncode(xdr);
                current.Name.XdrEncode(xdr);
                current.Attrs.XdrEncode(xdr);
                current = current.Nextentry;
                xdr.XdrEncodeBoolean(current != null);
            } while (current != null);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Entry4 current = this;
            Entry4 next;
            do
            {
                current.Cookie = new NfsCookie4(xdr);
                current.Name = new Component4(xdr);
                current.Attrs = new Fattr4(xdr);
                bool hasNext = xdr.XdrDecodeBoolean();
                next = hasNext ? new Entry4() : null;
                current.Nextentry = next;
                current = next;
            } while (current != null);
        }
    }
}
