/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result for the EXCHANGE_ID operation in NFSv4.
    /// </summary>
    public class ExchangeId4Resok : XdrAble
    {
        /// <summary>
        /// Gets or sets the eir clientid.
        /// </summary>
        public Clientid4 Eir_clientid;
        /// <summary>
        /// Gets or sets the eir sequenceid.
        /// </summary>
        public Sequenceid4 Eir_sequenceid;
        /// <summary>
        /// Gets or sets the eir flags.
        /// </summary>
        public Uint32T Eir_flags;
        /// <summary>
        /// Gets or sets the eir state protect.
        /// </summary>
        public StateProtect4R Eir_state_protect;
        /// <summary>
        /// Gets or sets the eir server owner.
        /// </summary>
        public ServerOwner4 Eir_server_owner;
        /// <summary>
        /// Gets or sets the eir server scope.
        /// </summary>
        public byte[] Eir_server_scope;
        /// <summary>
        /// Gets or sets the eir server impl id.
        /// </summary>
        public NfsImplId4[] Eir_server_impl_id;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExchangeId4Resok"/> class.
        /// </summary>
        public ExchangeId4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExchangeId4Resok"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public ExchangeId4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Eir_clientid.XdrEncode(xdr);
            Eir_sequenceid.XdrEncode(xdr);
            Eir_flags.XdrEncode(xdr);
            Eir_state_protect.XdrEncode(xdr);
            Eir_server_owner.XdrEncode(xdr);
            xdr.XdrEncodeDynamicOpaque(Eir_server_scope);
            { int size = Eir_server_impl_id.Length; xdr.XdrEncodeInt(size); for (int idx = 0; idx < size; ++idx) { Eir_server_impl_id[idx].XdrEncode(xdr); } }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Eir_clientid = new Clientid4(xdr);
            Eir_sequenceid = new Sequenceid4(xdr);
            Eir_flags = new Uint32T(xdr);
            Eir_state_protect = new StateProtect4R(xdr);
            Eir_server_owner = new ServerOwner4(xdr);
            Eir_server_scope = xdr.XdrDecodeDynamicOpaque();
            { int size = xdr.XdrDecodeInt(); Eir_server_impl_id = new NfsImplId4[size]; for (int idx = 0; idx < size; ++idx) { Eir_server_impl_id[idx] = new NfsImplId4(xdr); } }
        }
    }
}
