/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 quota_avail_soft file attribute.
    /// </summary>
    public class Fattr4QuotaAvailSoft : XdrAble
    {
        /// <summary>
        /// Gets or sets the soft quota limit for disk space available to the user in bytes.
        /// Represents a warning threshold that can be temporarily exceeded before the hard limit is enforced.
        /// </summary>
        public int Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4QuotaAvailSoft"/> class.
        /// </summary>
        public Fattr4QuotaAvailSoft()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4QuotaAvailSoft"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4QuotaAvailSoft(int Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4QuotaAvailSoft"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4QuotaAvailSoft(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Value);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeInt();
        }
    }
}
