/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 retention get attribute.
    /// </summary>
    public class Fattr4RetentionGet : XdrAble
    {
        /// <summary>
        /// Gets or sets the current retention policy information for the file.
        /// Defines how long the file must be retained before it can be deleted, typically for compliance purposes.
        /// </summary>
        public RetentionGet4 Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4RetentionGet"/> class.
        /// </summary>
        public Fattr4RetentionGet()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4RetentionGet"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4RetentionGet(RetentionGet4 Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4RetentionGet"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4RetentionGet(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new RetentionGet4(xdr);
        }
    }
}
