/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 lease_time file attribute.
    /// </summary>
    public class Fattr4LeaseTime : XdrAble
    {
        /// <summary>
        /// Gets or sets the duration of the lease time for client state in seconds.
        /// </summary>
        public NfsLease4 Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4LeaseTime"/> class.
        /// </summary>
        public Fattr4LeaseTime()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4LeaseTime"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4LeaseTime(NfsLease4 Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4LeaseTime"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4LeaseTime(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new NfsLease4(xdr);
        }
    }
}
