/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 chown_restricted file attribute.
    /// </summary>
    public class Fattr4ChownRestricted : XdrAble
    {
        /// <summary>
        /// Gets or sets a value indicating whether the file system restricts changing ownership of files.
        /// </summary>
        public bool Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4ChownRestricted"/> class.
        /// </summary>
        public Fattr4ChownRestricted()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4ChownRestricted"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4ChownRestricted(bool Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4ChownRestricted"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4ChownRestricted(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeBoolean(Value);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeBoolean();
        }
    }
}
