/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 access time set attribute.
    /// </summary>
    public class Fattr4TimeAccessSet : XdrAble
    {
        /// <summary>
        /// Gets or sets the desired access time to set for the file.
        /// Can be set to a specific time or to the server's current time, used in SETATTR operations.
        /// </summary>
        public Settime4 Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4TimeAccessSet"/> class.
        /// </summary>
        public Fattr4TimeAccessSet()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4TimeAccessSet"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4TimeAccessSet(Settime4 Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4TimeAccessSet"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4TimeAccessSet(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new Settime4(xdr);
        }
    }
}
