/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 supported attributes for exclusive create.
    /// </summary>
    public class Fattr4SuppattrExclcreat : XdrAble
    {
        /// <summary>
        /// Gets or sets the bitmap of attributes supported during exclusive file creation.
        /// Indicates which file attributes can be set atomically when creating a file with EXCLUSIVE4 mode.
        /// </summary>
        public Bitmap4 Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4SuppattrExclcreat"/> class.
        /// </summary>
        public Fattr4SuppattrExclcreat()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4SuppattrExclcreat"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4SuppattrExclcreat(Bitmap4 Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4SuppattrExclcreat"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4SuppattrExclcreat(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new Bitmap4(xdr);
        }
    }
}
