/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 dacl file attribute.
    /// </summary>
    public class Fattr4Dacl : XdrAble
    {
        /// <summary>
        /// Gets or sets the discretionary access control list (DACL) for the file or directory.
        /// </summary>
        public Nfsacl41 Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4Dacl"/> class.
        /// </summary>
        public Fattr4Dacl()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4Dacl"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4Dacl(Nfsacl41 Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4Dacl"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4Dacl(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new Nfsacl41(xdr);
        }
    }
}
