/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 mode_set_masked file attribute.
    /// </summary>
    public class Fattr4ModeSetMasked : XdrAble
    {
        /// <summary>
        /// Gets or sets the file mode (permissions) bits with a mask indicating which bits to set.
        /// </summary>
        public ModeMasked4 Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4ModeSetMasked"/> class.
        /// </summary>
        public Fattr4ModeSetMasked()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4ModeSetMasked"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4ModeSetMasked(ModeMasked4 Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4ModeSetMasked"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4ModeSetMasked(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new ModeMasked4(xdr);
        }
    }
}
