/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the ACL (Access Control List) attribute for NFSv4 files.
    /// </summary>
    public class Fattr4Acl : XdrAble
    {
        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        public Nfsace4[] Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4Acl"/> class.
        /// </summary>
        public Fattr4Acl()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4Acl"/> class with a specific value.
        /// </summary>
        /// <param name="value">The value.</param>
        public Fattr4Acl(Nfsace4[] value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4Acl"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4Acl(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            int size = Value.Length;
            xdr.XdrEncodeInt(size);
            for (int idx = 0; idx < size; ++idx)
            {
                Value[idx].XdrEncode(xdr);
            }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            int size = xdr.XdrDecodeInt();
            Value = new Nfsace4[size];
            for (int idx = 0; idx < size; ++idx)
            {
                Value[idx] = new Nfsace4(xdr);
            }
        }
    }
}
