/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 metadata change time attribute.
    /// </summary>
    public class Fattr4TimeMetadata : XdrAble
    {
        /// <summary>
        /// Gets or sets the time when the file's metadata was last changed.
        /// Updated when file attributes such as permissions, ownership, or links are modified (similar to Unix ctime).
        /// </summary>
        public Nfstime4 Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4TimeMetadata"/> class.
        /// </summary>
        public Fattr4TimeMetadata()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4TimeMetadata"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4TimeMetadata(Nfstime4 Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4TimeMetadata"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4TimeMetadata(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new Nfstime4(xdr);
        }
    }
}
