/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the can-set-time attribute for NFSv4 files.
    /// </summary>
    public class Fattr4Cansettime : XdrAble
    {
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        public bool Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4Cansettime"/> class.
        /// </summary>
        public Fattr4Cansettime()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4Cansettime"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4Cansettime(bool Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4Cansettime"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4Cansettime(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeBoolean(Value);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeBoolean();
        }
    }
}
