/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 retention set attribute.
    /// </summary>
    public class Fattr4RetentionSet : XdrAble
    {
        /// <summary>
        /// Gets or sets the retention policy settings for the file.
        /// Allows configuration of retention periods and policies for compliance and data governance requirements.
        /// </summary>
        public RetentionSet4 Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4RetentionSet"/> class.
        /// </summary>
        public Fattr4RetentionSet()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4RetentionSet"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public Fattr4RetentionSet(RetentionSet4 Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fattr4RetentionSet"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fattr4RetentionSet(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new RetentionSet4(xdr);
        }
    }
}
