/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /**
     * Enumeration (collection of constants).
     */

    public class Fs4StatusType
    {
        /// <summary>
        /// Status4 Fixed.
        /// </summary>
        public const int STATUS4_FIXED = 1;
        /// <summary>
        /// Status4 Updated.
        /// </summary>
        public const int STATUS4_UPDATED = 2;
        /// <summary>
        /// Status4 Versioned.
        /// </summary>
        public const int STATUS4_VERSIONED = 3;
        /// <summary>
        /// Status4 Writable.
        /// </summary>
        public const int STATUS4_WRITABLE = 4;
        /// <summary>
        /// Status4 Referral.
        /// </summary>
        public const int STATUS4_REFERRAL = 5;
    }
}
