/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 file system status structure.
    /// </summary>
    public class Fs4Status : XdrAble
    {
        /// <summary>
        /// Gets or sets the fss absent.
        /// </summary>
        public bool Fss_absent;
        /// <summary>
        /// Gets or sets the fss type.
        /// </summary>
        public int Fss_type;
        /// <summary>
        /// Gets or sets the fss source.
        /// </summary>
        public Utf8strCs Fss_source;
        /// <summary>
        /// Gets or sets the fss current.
        /// </summary>
        public Utf8strCs Fss_current;
        /// <summary>
        /// Gets or sets the fss age.
        /// </summary>
        public int Fss_age;
        /// <summary>
        /// Gets or sets the fss version.
        /// </summary>
        public Nfstime4 Fss_version;

        /// <summary>
        /// Initializes a new instance of the <see cref="Fs4Status"/> class.
        /// </summary>
        public Fs4Status()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Fs4Status"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Fs4Status(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Fss_type);
            Fss_source.XdrEncode(xdr);
            Fss_current.XdrEncode(xdr);
            xdr.XdrEncodeInt(Fss_age);
            Fss_version.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Fss_type = xdr.XdrDecodeInt();
            Fss_source = new Utf8strCs(xdr);
            Fss_current = new Utf8strCs(xdr);
            Fss_age = xdr.XdrDecodeInt();
            Fss_version = new Nfstime4(xdr);
        }
    }
}
