/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 character set capabilities.
    /// </summary>
    public class FsCharsetCap4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the Value.
        /// </summary>
        public int Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="FsCharsetCap4"/> class.
        /// </summary>
        public FsCharsetCap4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FsCharsetCap4"/> class with a specific Value.
        /// </summary>
        /// <param name="Value">The Value.</param>
        public FsCharsetCap4(int Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FsCharsetCap4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public FsCharsetCap4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Value);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeInt();
        }
    }
}
