/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the NFSv4 file system locations array.
    /// </summary>
    public class FsLocations4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the fs root.
        /// </summary>
        public Pathname4 Fs_root;
        /// <summary>
        /// Gets or sets the locations.
        /// </summary>
        public FsLocation4[] Locations;

        /// <summary>
        /// Initializes a new instance of the <see cref="FsLocations4"/> class.
        /// </summary>
        public FsLocations4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FsLocations4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public FsLocations4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            { int _size = Locations.Length; xdr.XdrEncodeInt(_size); for (int _idx = 0; _idx < _size; ++_idx) { Locations[_idx].XdrEncode(xdr); } }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            { int _size = xdr.XdrDecodeInt(); Locations = new FsLocation4[_size]; for (int _idx = 0; _idx < _size; ++_idx) { Locations[_idx] = new FsLocation4(xdr); } }
        }
    }
}
