/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the non-fatal result for the GET_DIR_DELEGATION operation in NFSv4.
    /// </summary>
    public class GetDirDelegation4ResNonFatal : XdrAble
    {
        /// <summary>
        /// Gets or sets the gddrnf status.
        /// </summary>
        public int Gddrnf_status;
        /// <summary>
        /// Gets or sets the gddrnf resok4.
        /// </summary>
        public GetDirDelegation4Resok Gddrnf_resok4;
        /// <summary>
        /// Gets or sets the gddrnf will signal deleg avail.
        /// </summary>
        public bool Gddrnf_will_signal_deleg_avail;

        /// <summary>
        /// Initializes a new instance of the <see cref="GetDirDelegation4ResNonFatal"/> class.
        /// </summary>
        public GetDirDelegation4ResNonFatal()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetDirDelegation4ResNonFatal"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public GetDirDelegation4ResNonFatal(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Gddrnf_status);
            switch (Gddrnf_status)
            {
                case Gddrnf4Status.GDD4_OK:
                    Gddrnf_resok4.XdrEncode(xdr);
                    break;

                case Gddrnf4Status.GDD4_UNAVAIL:
                    xdr.XdrEncodeBoolean(Gddrnf_will_signal_deleg_avail);
                    break;
            }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Gddrnf_status = xdr.XdrDecodeInt();
            switch (Gddrnf_status)
            {
                case Gddrnf4Status.GDD4_OK:
                    Gddrnf_resok4 = new GetDirDelegation4Resok(xdr);
                    break;

                case Gddrnf4Status.GDD4_UNAVAIL:
                    Gddrnf_will_signal_deleg_avail = xdr.XdrDecodeBoolean();
                    break;
            }
        }
    }
}
