/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result for the GET_DIR_DELEGATION operation in NFSv4.
    /// </summary>
    public class GetDirDelegation4Resok : XdrAble
    {
        /// <summary>
        /// Gets or sets the gddr cookieverf.
        /// </summary>
        public Verifier4 Gddr_cookieverf;
        /// <summary>
        /// Gets or sets the gddr stateid.
        /// </summary>
        public Stateid4 Gddr_stateid;
        /// <summary>
        /// Gets or sets the gddr notification.
        /// </summary>
        public Bitmap4 Gddr_notification;
        /// <summary>
        /// Gets or sets the gddr child attributes.
        /// </summary>
        public Bitmap4 Gddr_child_attributes;
        /// <summary>
        /// Gets or sets the gddr dir attributes.
        /// </summary>
        public Bitmap4 Gddr_dir_attributes;

        /// <summary>
        /// Initializes a new instance of the <see cref="GetDirDelegation4Resok"/> class.
        /// </summary>
        public GetDirDelegation4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetDirDelegation4Resok"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public GetDirDelegation4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Gddr_stateid.XdrEncode(xdr);
            Gddr_notification.XdrEncode(xdr);
            Gddr_child_attributes.XdrEncode(xdr);
            Gddr_dir_attributes.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Gddr_stateid = new Stateid4(xdr);
            Gddr_notification = new Bitmap4(xdr);
            Gddr_child_attributes = new Bitmap4(xdr);
            Gddr_dir_attributes = new Bitmap4(xdr);
        }
    }
}
