/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result for the GETDEVICELIST operation in NFSv4.
    /// </summary>
    public class Getdevicelist4Resok : XdrAble
    {
        /// <summary>
        /// Gets or sets the gdlr cookie.
        /// </summary>
        public NfsCookie4 Gdlr_cookie;
        /// <summary>
        /// Gets or sets the gdlr cookieverf.
        /// </summary>
        public Verifier4 Gdlr_cookieverf;
        /// <summary>
        /// Gets or sets the gdlr deviceid list.
        /// </summary>
        public Deviceid4[] gdlr_deviceid_list;
        /// <summary>
        /// Gets or sets the gdlr eof.
        /// </summary>
        public bool Gdlr_eof;

        /// <summary>
        /// Initializes a new instance of the <see cref="Getdevicelist4Resok"/> class.
        /// </summary>
        public Getdevicelist4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Getdevicelist4Resok"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Getdevicelist4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Gdlr_cookieverf.XdrEncode(xdr);
            { int size = gdlr_deviceid_list.Length; xdr.XdrEncodeInt(size); for (int idx = 0; idx < size; ++idx) { gdlr_deviceid_list[idx].XdrEncode(xdr); } }
            xdr.XdrEncodeBoolean(Gdlr_eof);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Gdlr_cookieverf = new Verifier4(xdr);
            { int size = xdr.XdrDecodeInt(); gdlr_deviceid_list = new Deviceid4[size]; for (int idx = 0; idx < size; ++idx) { gdlr_deviceid_list[idx] = new Deviceid4(xdr); } }
            Gdlr_eof = xdr.XdrDecodeBoolean();
        }
    }
}
