/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result for the GET_DIR_DELEGATION operation in NFSv4.
    /// </summary>
    public class GetDirDelegation4Res : XdrAble
    {
        /// <summary>
        /// Gets or sets the gddr status.
        /// </summary>
        public int Gddr_status;
        /// <summary>
        /// Gets or sets the gddr res non fatal4.
        /// </summary>
        public GetDirDelegation4ResNonFatal Gddr_res_non_fatal4;

        /// <summary>
        /// Initializes a new instance of the <see cref="GetDirDelegation4Res"/> class.
        /// </summary>
        public GetDirDelegation4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetDirDelegation4Res"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public GetDirDelegation4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Gddr_status);
            switch (Gddr_status)
            {
                case Nfsstat4.NFS4_OK:
                    Gddr_res_non_fatal4.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Gddr_status = xdr.XdrDecodeInt();
            switch (Gddr_status)
            {
                case Nfsstat4.NFS4_OK:
                    Gddr_res_non_fatal4 = new GetDirDelegation4ResNonFatal(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
