/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result for the GETDEVICEINFO operation in NFSv4.
    /// </summary>
    public class Getdeviceinfo4Res : XdrAble
    {
        /// <summary>
        /// Gets or sets the gdir status.
        /// </summary>
        public int Gdir_status;
        /// <summary>
        /// Gets or sets the gdir resok4.
        /// </summary>
        public Getdeviceinfo4Resok Gdir_resok4;
        /// <summary>
        /// Gets or sets the gdir mincount.
        /// </summary>
        public Count4 Gdir_mincount;

        /// <summary>
        /// Initializes a new instance of the <see cref="Getdeviceinfo4Res"/> class.
        /// </summary>
        public Getdeviceinfo4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Getdeviceinfo4Res"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Getdeviceinfo4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Gdir_status);
            switch (Gdir_status)
            {
                case Nfsstat4.NFS4_OK:
                    Gdir_resok4.XdrEncode(xdr);
                    break;

                case Nfsstat4.NFS4ERR_TOOSMALL:
                    Gdir_mincount.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Gdir_status = xdr.XdrDecodeInt();
            switch (Gdir_status)
            {
                case Nfsstat4.NFS4_OK:
                    Gdir_resok4 = new Getdeviceinfo4Resok(xdr);
                    break;

                case Nfsstat4.NFS4ERR_TOOSMALL:
                    Gdir_mincount = new Count4(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
