/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a GSS handle for NFSv4 protocol.
    /// </summary>
    public class Gsshandle4T : XdrAble
    {
        /// <summary>
        /// Gets or sets the value.
        /// </summary>
        public byte[] Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Gsshandle4T"/> class.
        /// </summary>
        public Gsshandle4T()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Gsshandle4T"/> class with a specific value.
        /// </summary>
        /// <param name="value">The value.</param>
        public Gsshandle4T(byte[] value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Gsshandle4T"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Gsshandle4T(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeDynamicOpaque(Value);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeDynamicOpaque();
        }
    }
}
