/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of an illegal NFSv4 operation.
    /// </summary>
    public class Illegal4Res : XdrAble
    {
        /// <summary>
        /// Gets or sets the status code for the illegal operation.
        /// </summary>
        public int Status;

        /// <summary>
        /// Initializes a new instance of the <see cref="Illegal4Res"/> class.
        /// </summary>
        public Illegal4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Illegal4Res"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Illegal4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
