/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result of a LAYOUTGET operation in NFSv4.
    /// </summary>
    public class Layoutget4Resok : XdrAble
    {
        /// <summary>
        /// Gets or sets a value indicating whether to return the layout on close.
        /// </summary>
        public bool Logr_return_on_close;

        /// <summary>
        /// Gets or sets the stateid for the layout.
        /// </summary>
        public Stateid4 Logr_stateid;

        /// <summary>
        /// Gets or sets the array of layouts.
        /// </summary>
        public Layout4[] logr_layout;

        /// <summary>
        /// Initializes a new instance of the <see cref="Layoutget4Resok"/> class.
        /// </summary>
        public Layoutget4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Layoutget4Resok"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Layoutget4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Logr_stateid.XdrEncode(xdr);
            { int size = logr_layout.Length; xdr.XdrEncodeInt(size); for (int idx = 0; idx < size; ++idx) { logr_layout[idx].XdrEncode(xdr); } }
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Logr_stateid = new Stateid4(xdr);
            { int size = xdr.XdrDecodeInt(); logr_layout = new Layout4[size]; for (int idx = 0; idx < size; ++idx) { logr_layout[idx] = new Layout4(xdr); } }
        }
    }
}
