/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of a LAYOUTGET operation in NFSv4.
    /// </summary>
    public class Layoutget4Res : XdrAble
    {
        /// <summary>
        /// Gets or sets the status of the operation.
        /// </summary>
        public int Logr_status;

        /// <summary>
        /// Gets or sets the successful result data.
        /// </summary>
        public Layoutget4Resok Logr_resok4;

        /// <summary>
        /// Gets or sets a value indicating whether the server will signal layout availability.
        /// </summary>
        public bool Logr_will_signal_layout_avail;

        /// <summary>
        /// Initializes a new instance of the <see cref="Layoutget4Res"/> class.
        /// </summary>
        public Layoutget4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Layoutget4Res"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Layoutget4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Logr_status);
            switch (Logr_status)
            {
                case Nfsstat4.NFS4_OK:
                    Logr_resok4.XdrEncode(xdr);
                    break;

                case Nfsstat4.NFS4ERR_LAYOUTTRYLATER:
                    xdr.XdrEncodeBoolean(Logr_will_signal_layout_avail);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Logr_status = xdr.XdrDecodeInt();
            switch (Logr_status)
            {
                case Nfsstat4.NFS4_OK:
                    Logr_resok4 = new Layoutget4Resok(xdr);
                    break;

                case Nfsstat4.NFS4ERR_LAYOUTTRYLATER:
                    Logr_will_signal_layout_avail = xdr.XdrDecodeBoolean();
                    break;

                default:
                    break;
            }
        }
    }
}
