/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents layout content for NFSv4.1 pNFS.
    /// </summary>
    public class LayoutContent4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the layout type.
        /// </summary>
        public int Loc_type;

        /// <summary>
        /// Gets or sets the layout-specific body content.
        /// </summary>
        public byte[] Loc_body;

        /// <summary>
        /// Initializes a new instance of the <see cref="LayoutContent4"/> class.
        /// </summary>
        public LayoutContent4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LayoutContent4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public LayoutContent4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeDynamicOpaque(Loc_body);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Loc_body = xdr.XdrDecodeDynamicOpaque();
        }
    }
}
