/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the LAYOUTRETURN operation in NFSv4.
    /// </summary>
    public class Layoutreturn4Args : XdrAble
    {
        /// <summary>
        /// Gets or sets a value indicating whether this is a reclaim operation.
        /// </summary>
        public bool Lora_reclaim;

        /// <summary>
        /// Gets or sets the layout type.
        /// </summary>
        public int Lora_layout_type;

        /// <summary>
        /// Gets or sets the I/O mode.
        /// </summary>
        public int Lora_iomode;

        /// <summary>
        /// Gets or sets the layout return information.
        /// </summary>
        public Layoutreturn4 Lora_layoutreturn;

        /// <summary>
        /// Initializes a new instance of the <see cref="Layoutreturn4Args"/> class.
        /// </summary>
        public Layoutreturn4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Layoutreturn4Args"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Layoutreturn4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Lora_layout_type);
            xdr.XdrEncodeInt(Lora_iomode);
            Lora_layoutreturn.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Lora_layout_type = xdr.XdrDecodeInt();
            Lora_iomode = xdr.XdrDecodeInt();
            Lora_layoutreturn = new Layoutreturn4(xdr);
        }
    }
}
