/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /// <summary>
    /// Enumeration of layout I/O modes for NFSv4.1 pNFS.
    /// </summary>
    public class Layoutiomode4
    {
        /// <summary>
        /// Read-only layout I/O mode.
        /// </summary>
        public const int LAYOUTIOMODE4_READ = 1;

        /// <summary>
        /// Read-write layout I/O mode.
        /// </summary>
        public const int LAYOUTIOMODE4_RW = 2;

        /// <summary>
        /// Any layout I/O mode.
        /// </summary>
        public const int LAYOUTIOMODE4_ANY = 3;
    }
}
