/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of a LAYOUTCOMMIT operation in NFSv4.
    /// </summary>
    public class Layoutcommit4Res : XdrAble
    {
        /// <summary>
        /// Gets or sets the status of the operation.
        /// </summary>
        public int Locr_status;

        /// <summary>
        /// Gets or sets the successful result data.
        /// </summary>
        public Layoutcommit4Resok Locr_resok4;

        /// <summary>
        /// Initializes a new instance of the <see cref="Layoutcommit4Res"/> class.
        /// </summary>
        public Layoutcommit4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Layoutcommit4Res"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Layoutcommit4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Locr_status);
            switch (Locr_status)
            {
                case Nfsstat4.NFS4_OK:
                    Locr_resok4.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Locr_status = xdr.XdrDecodeInt();
            switch (Locr_status)
            {
                case Nfsstat4.NFS4_OK:
                    Locr_resok4 = new Layoutcommit4Resok(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
