/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents symbolic link text for NFSv4 protocol.
    /// </summary>
    public class Linktext4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the symbolic link text Value.
        /// </summary>
        public Utf8strCs Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Linktext4"/> class.
        /// </summary>
        public Linktext4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Linktext4"/> class with the specified Value.
        /// </summary>
        /// <param name="Value">The symbolic link text Value.</param>
        public Linktext4(Utf8strCs Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Linktext4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Linktext4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new Utf8strCs(xdr);
        }
    }
}
