/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result of a LINK operation in NFSv4.
    /// </summary>
    public class Link4Resok : XdrAble
    {
        /// <summary>
        /// Change information for the directory in which the hard link was created.
        /// </summary>
        public ChangeInfo4 Cinfo;

        /// <summary>
        /// Initializes a new instance of the <see cref="Link4Resok"/> class.
        /// </summary>
        public Link4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Link4Resok"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Link4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
