/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of a LOCKU (unlock) operation in NFSv4.
    /// </summary>
    public class Locku4Res : XdrAble
    {
        /// <summary>
        /// The status of the LOCKU operation.
        /// </summary>
        public int Status;

        /// <summary>
        /// The updated state ID after the unlock (populated when status is NFS4_OK).
        /// </summary>
        public Stateid4 Lock_stateid;

        /// <summary>
        /// Initializes a new instance of the <see cref="Locku4Res"/> class.
        /// </summary>
        public Locku4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Locku4Res"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Locku4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Status);
            switch (Status)
            {
                case Nfsstat4.NFS4_OK:
                    Lock_stateid.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Status = xdr.XdrDecodeInt();
            switch (Status)
            {
                case Nfsstat4.NFS4_OK:
                    Lock_stateid = new Stateid4(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
