/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the LOOKUP operation in NFSv4.
    /// </summary>
    public class Lookup4Args : XdrAble
    {
        /// <summary>
        /// The name of the object to look up in the current directory.
        /// </summary>
        public Component4 Objname;

        /// <summary>
        /// Initializes a new instance of the <see cref="Lookup4Args"/> class.
        /// </summary>
        public Lookup4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Lookup4Args"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Lookup4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Objname.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Objname = new Component4(xdr);
        }
    }
}
