/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a new time value for NFSv4 protocol.
    /// </summary>
    public class Newtime4 : XdrAble
    {
        /// <summary>Gets or sets a value indicating whether the time has changed.</summary>
        public bool Nt_timechanged;

        /// <summary>Gets or sets the new time value when changed.</summary>
        public Nfstime4 Nt_time;

        /// <summary>Initializes a new instance of the <see cref="Newtime4"/> class.</summary>
        public Newtime4()
        {
        }

        /// <summary>Initializes a new instance of the <see cref="Newtime4"/> class.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Newtime4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>Encodes this object to XDR format.</summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeBoolean(Nt_timechanged);
            if (Nt_timechanged == true)
            {
                Nt_time.XdrEncode(xdr);
            }
        }

        /// <summary>Decodes this object from XDR format.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Nt_timechanged = xdr.XdrDecodeBoolean();
            if (Nt_timechanged == true)
            {
                Nt_time = new Nfstime4(xdr);
            }
        }
    }
}
