/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents an NFS client identifier for NFSv4 protocol.
    /// </summary>
    public class NfsClientId4 : XdrAble
    {
        /// <summary>Gets or sets the verifier for client identification.</summary>
        public Verifier4 Verifier;

        /// <summary>Gets or sets the opaque client identifier bytes.</summary>
        public byte[] Id;

        /// <summary>Initializes a new instance of the <see cref="NfsClientId4"/> class.</summary>
        public NfsClientId4()
        {
        }

        /// <summary>Initializes a new instance of the <see cref="NfsClientId4"/> class.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NfsClientId4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>Encodes this object to XDR format.</summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeDynamicOpaque(Id);
        }

        /// <summary>Decodes this object from XDR format.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Id = xdr.XdrDecodeDynamicOpaque();
        }
    }
}
