/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a file handle for NFSv4 protocol.
    /// </summary>
    public class NfsFh4 : XdrAble
    {
        /// <summary>
        /// The opaque file handle data used to uniquely identify a file or directory on the NFS server.
        /// This is an opaque byte array whose structure is determined by the server implementation.
        /// </summary>
        public byte[] Value;

        /// <summary>Initializes a new instance of the <see cref="NfsFh4"/> class.</summary>
        public NfsFh4()
        {
        }

        /// <summary>Initializes a new instance of the <see cref="NfsFh4"/> class.</summary>
        /// <param name="value">The file handle bytes.</param>
        public NfsFh4(byte[] value)
        {
            this.Value = value;
        }

        /// <summary>Initializes a new instance of the <see cref="NfsFh4"/> class.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NfsFh4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>Encodes this object to XDR format.</summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeDynamicOpaque(Value);
        }

        /// <summary>Decodes this object from XDR format.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeDynamicOpaque();
        }
    }
}
