/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents an NFS implementation identifier for NFSv4 protocol.
    /// </summary>
    public class NfsImplId4 : XdrAble
    {
        /// <summary>Gets or sets the domain name of the NFS implementation.</summary>
        public Utf8strCis Nii_domain;

        /// <summary>Gets or sets the name of the NFS implementation.</summary>
        public Utf8strCs Nii_name;

        /// <summary>Gets or sets the build date/time of the NFS implementation.</summary>
        public Nfstime4 Nii_date;

        /// <summary>Initializes a new instance of the <see cref="NfsImplId4"/> class.</summary>
        public NfsImplId4()
        {
        }

        /// <summary>Initializes a new instance of the <see cref="NfsImplId4"/> class.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NfsImplId4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>Encodes this object to XDR format.</summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Nii_domain.XdrEncode(xdr);
            Nii_name.XdrEncode(xdr);
            Nii_date.XdrEncode(xdr);
        }

        /// <summary>Decodes this object from XDR format.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Nii_domain = new Utf8strCis(xdr);
            Nii_name = new Utf8strCs(xdr);
            Nii_date = new Nfstime4(xdr);
        }
    }
}
