/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a lease time value for NFSv4 protocol.
    /// </summary>
    public class NfsLease4 : XdrAble
    {
        /// <summary>Gets or sets the lease time value in seconds.</summary>
        public int Value;

        /// <summary>Initializes a new instance of the <see cref="NfsLease4"/> class.</summary>
        public NfsLease4()
        {
        }

        /// <summary>Initializes a new instance of the <see cref="NfsLease4"/> class.</summary>
        /// <param name="value">The lease time value in seconds.</param>
        public NfsLease4(int value)
        {
            this.Value = value;
        }

        /// <summary>Initializes a new instance of the <see cref="NfsLease4"/> class.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NfsLease4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>Encodes this object to XDR format.</summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Value);
        }

        /// <summary>Decodes this object from XDR format.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeInt();
        }
    }
}
