/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a modified block limit for NFSv4 protocol.
    /// </summary>
    public class NfsModifiedLimit4 : XdrAble
    {
        /// <summary>Gets or sets the number of modified blocks.</summary>
        public int Num_blocks;

        /// <summary>Gets or sets the number of bytes per block.</summary>
        public int Bytes_per_block;

        /// <summary>Initializes a new instance of the <see cref="NfsModifiedLimit4"/> class.</summary>
        public NfsModifiedLimit4()
        {
        }

        /// <summary>Initializes a new instance of the <see cref="NfsModifiedLimit4"/> class.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NfsModifiedLimit4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>Encodes this object to XDR format.</summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Bytes_per_block);
        }

        /// <summary>Decodes this object from XDR format.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Bytes_per_block = xdr.XdrDecodeInt();
        }
    }
}
