/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /// <summary>
    /// Defines operation numbers for NFSv4 protocol compound operations.
    /// </summary>
    public class NfsOpnum4
    {
        /// <summary>Check access permission.</summary>
        public const int OP_ACCESS = 3;
        /// <summary>Close file.</summary>
        public const int OP_CLOSE = 4;
        /// <summary>Commit cached data.</summary>
        public const int OP_COMMIT = 5;
        /// <summary>Create a non-regular file object.</summary>
        public const int OP_CREATE = 6;
        /// <summary>Purge delegations awaiting recovery.</summary>
        public const int OP_DELEGPURGE = 7;
        /// <summary>Return a delegation.</summary>
        public const int OP_DELEGRETURN = 8;
        /// <summary>Get attributes.</summary>
        public const int OP_GETATTR = 9;
        /// <summary>Get current file handle.</summary>
        public const int OP_GETFH = 10;
        /// <summary>Create link to a file.</summary>
        public const int OP_LINK = 11;
        /// <summary>Create lock.</summary>
        public const int OP_LOCK = 12;
        /// <summary>Test for lock.</summary>
        public const int OP_LOCKT = 13;
        /// <summary>Unlock file.</summary>
        public const int OP_LOCKU = 14;
        /// <summary>Lookup filename.</summary>
        public const int OP_LOOKUP = 15;
        /// <summary>Lookup parent directory.</summary>
        public const int OP_LOOKUPP = 16;
        /// <summary>Verify difference in attributes.</summary>
        public const int OP_NVERIFY = 17;
        /// <summary>Open a file.</summary>
        public const int OP_OPEN = 18;
        /// <summary>Open named attribute directory.</summary>
        public const int OP_OPENATTR = 19;
        /// <summary>Confirm open (NFSv4.0).</summary>
        public const int OP_OPEN_CONFIRM = 20;
        /// <summary>Reduce open file access.</summary>
        public const int OP_OPEN_DOWNGRADE = 21;
        /// <summary>Set current file handle.</summary>
        public const int OP_PUTFH = 22;
        /// <summary>Set public file handle.</summary>
        public const int OP_PUTPUBFH = 23;
        /// <summary>Set root file handle.</summary>
        public const int OP_PUTROOTFH = 24;
        /// <summary>Read from file.</summary>
        public const int OP_READ = 25;
        /// <summary>Read directory.</summary>
        public const int OP_READDIR = 26;
        /// <summary>Read symbolic link.</summary>
        public const int OP_READLINK = 27;
        /// <summary>Remove file system object.</summary>
        public const int OP_REMOVE = 28;
        /// <summary>Rename file system object.</summary>
        public const int OP_RENAME = 29;
        /// <summary>Renew a lease.</summary>
        public const int OP_RENEW = 30;
        /// <summary>Restore saved file handle.</summary>
        public const int OP_RESTOREFH = 31;
        /// <summary>Save current file handle.</summary>
        public const int OP_SAVEFH = 32;
        /// <summary>Obtain security information.</summary>
        public const int OP_SECINFO = 33;
        /// <summary>Set attributes.</summary>
        public const int OP_SETATTR = 34;
        /// <summary>Set client ID (NFSv4.0).</summary>
        public const int OP_SETCLIENTID = 35;
        /// <summary>Confirm client ID (NFSv4.0).</summary>
        public const int OP_SETCLIENTID_CONFIRM = 36;
        /// <summary>Verify attributes.</summary>
        public const int OP_VERIFY = 37;
        /// <summary>Write to file.</summary>
        public const int OP_WRITE = 38;
        /// <summary>Release lock owner state.</summary>
        public const int OP_RELEASE_LOCKOWNER = 39;
        /// <summary>Back channel control.</summary>
        public const int OP_BACKCHANNEL_CTL = 40;
        /// <summary>Bind connection to session.</summary>
        public const int OP_BIND_CONN_TO_SESSION = 41;
        /// <summary>Exchange client owner ID.</summary>
        public const int OP_EXCHANGE_ID = 42;
        /// <summary>Create a new session.</summary>
        public const int OP_CREATE_SESSION = 43;
        /// <summary>Destroy a session.</summary>
        public const int OP_DESTROY_SESSION = 44;
        /// <summary>Free state ID.</summary>
        public const int OP_FREE_STATEID = 45;
        /// <summary>Get directory delegation.</summary>
        public const int OP_GET_DIR_DELEGATION = 46;
        /// <summary>Get device information.</summary>
        public const int OP_GETDEVICEINFO = 47;
        /// <summary>Get device list.</summary>
        public const int OP_GETDEVICELIST = 48;
        /// <summary>Commit pNFS layout.</summary>
        public const int OP_LAYOUTCOMMIT = 49;
        /// <summary>Get pNFS layout.</summary>
        public const int OP_LAYOUTGET = 50;
        /// <summary>Return pNFS layout.</summary>
        public const int OP_LAYOUTRETURN = 51;
        /// <summary>Get security info by style.</summary>
        public const int OP_SECINFO_NO_NAME = 52;
        /// <summary>Supply per-compound session info.</summary>
        public const int OP_SEQUENCE = 53;
        /// <summary>Set session security verifier.</summary>
        public const int OP_SET_SSV = 54;
        /// <summary>Test state IDs for validity.</summary>
        public const int OP_TEST_STATEID = 55;
        /// <summary>Request a delegation.</summary>
        public const int OP_WANT_DELEGATION = 56;
        /// <summary>Destroy client ID.</summary>
        public const int OP_DESTROY_CLIENTID = 57;
        /// <summary>Indicate locks reclaimed.</summary>
        public const int OP_RECLAIM_COMPLETE = 58;
        /// <summary>Illegal operation.</summary>
        public const int OP_ILLEGAL = 10044;
    }
}
