/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a space limit for NFSv4 protocol.
    /// </summary>
    public class NfsSpaceLimit4 : XdrAble
    {
        /// <summary>Gets or sets the limit type (by size or by blocks).</summary>
        public int Limitby;

        /// <summary>Gets or sets the file size limit when limiting by size.</summary>
        public int Filesize;

        /// <summary>Gets or sets the modified blocks limit when limiting by blocks.</summary>
        public NfsModifiedLimit4 Mod_blocks;

        /// <summary>Initializes a new instance of the <see cref="NfsSpaceLimit4"/> class.</summary>
        public NfsSpaceLimit4()
        {
        }

        /// <summary>Initializes a new instance of the <see cref="NfsSpaceLimit4"/> class.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NfsSpaceLimit4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>Encodes this object to XDR format.</summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Limitby);
            switch (Limitby)
            {
                case LimitBy4.NFS_LIMIT_SIZE:
                    xdr.XdrEncodeInt(Filesize);
                    break;

                case LimitBy4.NFS_LIMIT_BLOCKS:
                    Mod_blocks.XdrEncode(xdr);
                    break;
            }
        }

        /// <summary>Decodes this object from XDR format.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Limitby = xdr.XdrDecodeInt();
            switch (Limitby)
            {
                case LimitBy4.NFS_LIMIT_SIZE:
                    Filesize = xdr.XdrDecodeInt();
                    break;

                case LimitBy4.NFS_LIMIT_BLOCKS:
                    Mod_blocks = new NfsModifiedLimit4(xdr);
                    break;
            }
        }
    }
}
