/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;
    using NFSLibrary.Rpc.Server;
    using System.Net;

    /// <summary>
    /// Abstract base class for NFSv4 protocol server implementation.
    /// Handles ONC/RPC call dispatching and provides abstract methods for NFSv4 procedure implementations.
    /// </summary>
    public abstract class NFSv4ProtocolServerStub : OncRpcServerStub, OncRpcDispatchable
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv4ProtocolServerStub"/> class using the default port.
        /// </summary>
        public NFSv4ProtocolServerStub() : this(0)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv4ProtocolServerStub"/> class with a specified port.
        /// </summary>
        /// <param name="port">The port number on which to listen for incoming requests.</param>
        public NFSv4ProtocolServerStub(int port) : this(null, port)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSv4ProtocolServerStub"/> class with a specified bind address and port.
        /// </summary>
        /// <param name="bindAddr">The IP address to bind to.</param>
        /// <param name="port">The port number on which to listen for incoming requests.</param>
        public NFSv4ProtocolServerStub(IPAddress bindAddr, int port)
        {
            Info = new OncRpcServerTransportRegistrationInfo[] {
            new OncRpcServerTransportRegistrationInfo(NFSv4Protocol.NFS4_PROGRAM, 4),
        };
            Transports = new OncRpcServerTransport[] {
            new OncRpcUdpServerTransport(this, bindAddr, port, Info, 32768),
            new OncRpcTcpServerTransport(this, bindAddr, port, Info, 32768)
        };
        }

        /// <summary>
        /// Dispatches incoming ONC/RPC calls to the appropriate procedure implementation.
        /// </summary>
        /// <param name="call">Information about the incoming call.</param>
        /// <param name="program">The program number.</param>
        /// <param name="version">The version number.</param>
        /// <param name="procedure">The procedure number to execute.</param>
        public void DispatchOncRpcCall(OncRpcCallInformation call, int program, int version, int procedure)
        {
            if (version == 4)
            {
                switch (procedure)
                {
                    case 0:
                        {
                            call.retrieveCall(XdrVoid.XDR_VOID);
                            NFSPROC4_NULL_4();
                            call.reply(XdrVoid.XDR_VOID);
                            break;
                        }
                    case 1:
                        {
                            Compound4Args args_ = new Compound4Args();
                            call.retrieveCall(args_);
                            Compound4Res result_ = NFSPROC4_COMPOUND_4(args_);
                            call.reply(result_);
                            break;
                        }
                    default:
                        call.failProcedureUnavailable();
                        break;
                }
            }
            else
            {
                call.failProgramUnavailable();
            }
        }

        /// <summary>
        /// Implements the NFSPROC4_NULL_4 procedure.
        /// This is a null procedure typically used for testing connectivity.
        /// </summary>
        public abstract void NFSPROC4_NULL_4();

        /// <summary>
        /// Implements the NFSPROC4_COMPOUND_4 procedure.
        /// This procedure executes a compound operation consisting of multiple NFSv4 operations.
        /// </summary>
        /// <param name="arg1">The compound operation arguments.</param>
        /// <returns>The result of the compound operation.</returns>
        public abstract Compound4Res NFSPROC4_COMPOUND_4(Compound4Args arg1);
    }
}
