/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the NVERIFY operation in NFSv4 protocol.
    /// </summary>
    public class Nverify4Args : XdrAble
    {
        /// <summary>Gets or sets the file attributes to verify do not match.</summary>
        public Fattr4 Obj_attributes;

        /// <summary>Initializes a new instance of the <see cref="Nverify4Args"/> class.</summary>
        public Nverify4Args()
        {
        }

        /// <summary>Initializes a new instance of the <see cref="Nverify4Args"/> class.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Nverify4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>Encodes this object to XDR format.</summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>Decodes this object from XDR format.</summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
