/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a write delegation for NFSv4 OPEN operation.
    /// </summary>
    public class OpenWriteDelegation4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the delegation state identifier.
        /// </summary>
        public Stateid4 Stateid;

        /// <summary>
        /// Gets or sets a value indicating whether the delegation is subject to recall.
        /// </summary>
        public bool Recall;

        /// <summary>
        /// Gets or sets the space limit for the delegation.
        /// </summary>
        public NfsSpaceLimit4 Space_limit;

        /// <summary>
        /// Gets or sets the permissions granted with the delegation.
        /// </summary>
        public Nfsace4 Permissions;

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenWriteDelegation4"/> class.
        /// </summary>
        public OpenWriteDelegation4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenWriteDelegation4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public OpenWriteDelegation4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the OpenWriteDelegation4 data structure to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeBoolean(Recall);
            Space_limit.XdrEncode(xdr);
            Permissions.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the OpenWriteDelegation4 data structure from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Recall = xdr.XdrDecodeBoolean();
            Space_limit = new NfsSpaceLimit4(xdr);
            Permissions = new Nfsace4(xdr);
        }
    }
}
