/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents conversion from open owner to lock owner in NFSv4 protocol.
    /// </summary>
    public class OpenToLockOwner4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the sequence identifier for the open owner.
        /// </summary>
        public Seqid4 Open_seqid;

        /// <summary>
        /// Gets or sets the state identifier for the open file.
        /// </summary>
        public Stateid4 Open_stateid;

        /// <summary>
        /// Gets or sets the sequence identifier for the lock owner.
        /// </summary>
        public Seqid4 Lock_seqid;

        /// <summary>
        /// Gets or sets the lock owner information.
        /// </summary>
        public LockOwner4 Lock_owner;

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenToLockOwner4"/> class.
        /// </summary>
        public OpenToLockOwner4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenToLockOwner4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public OpenToLockOwner4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the OpenToLockOwner4 data structure to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Open_stateid.XdrEncode(xdr);
            Lock_seqid.XdrEncode(xdr);
            Lock_owner.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the OpenToLockOwner4 data structure from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Open_stateid = new Stateid4(xdr);
            Lock_seqid = new Seqid4(xdr);
            Lock_owner = new LockOwner4(xdr);
        }
    }
}
