/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a none delegation response for NFSv4 OPEN operation.
    /// </summary>
    public class OpenNoneDelegation4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the reason why no delegation was granted.
        /// </summary>
        public int Ond_why;

        /// <summary>
        /// Gets or sets a value indicating whether the server will push a delegation when contention subsides.
        /// </summary>
        public bool Ond_server_will_push_deleg;

        /// <summary>
        /// Gets or sets a value indicating whether the server will signal when resources become available.
        /// </summary>
        public bool Ond_server_will_signal_avail;

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenNoneDelegation4"/> class.
        /// </summary>
        public OpenNoneDelegation4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenNoneDelegation4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public OpenNoneDelegation4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the OpenNoneDelegation4 data structure to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Ond_why);
            switch (Ond_why)
            {
                case WhyNoDelegation4.WND4_CONTENTION:
                    xdr.XdrEncodeBoolean(Ond_server_will_push_deleg);
                    break;

                case WhyNoDelegation4.WND4_RESOURCE:
                    xdr.XdrEncodeBoolean(Ond_server_will_signal_avail);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes the OpenNoneDelegation4 data structure from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Ond_why = xdr.XdrDecodeInt();
            switch (Ond_why)
            {
                case WhyNoDelegation4.WND4_CONTENTION:
                    Ond_server_will_push_deleg = xdr.XdrDecodeBoolean();
                    break;

                case WhyNoDelegation4.WND4_RESOURCE:
                    Ond_server_will_signal_avail = xdr.XdrDecodeBoolean();
                    break;

                default:
                    break;
            }
        }
    }
}
