/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the OPENATTR operation in NFSv4 protocol.
    /// </summary>
    public class Openattr4Args : XdrAble
    {
        /// <summary>
        /// Gets or sets a value indicating whether to create the named attribute directory if it does not exist.
        /// </summary>
        public bool Createdir;

        /// <summary>
        /// Initializes a new instance of the <see cref="Openattr4Args"/> class.
        /// </summary>
        public Openattr4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Openattr4Args"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Openattr4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the Openattr4Args data structure to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes the Openattr4Args data structure from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
