/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of the OPEN_DOWNGRADE operation in NFSv4 protocol.
    /// </summary>
    public class OpenDowngrade4Res : XdrAble
    {
        /// <summary>
        /// Gets or sets the status of the OPEN_DOWNGRADE operation.
        /// </summary>
        public int Status;

        /// <summary>
        /// Gets or sets the successful result data when status is NFS4_OK.
        /// </summary>
        public OpenDowngrade4Resok Resok4;

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenDowngrade4Res"/> class.
        /// </summary>
        public OpenDowngrade4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="OpenDowngrade4Res"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public OpenDowngrade4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the OpenDowngrade4Res data structure to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Status);
            switch (Status)
            {
                case Nfsstat4.NFS4_OK:
                    Resok4.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes the OpenDowngrade4Res data structure from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Status = xdr.XdrDecodeInt();
            switch (Status)
            {
                case Nfsstat4.NFS4_OK:
                    Resok4 = new OpenDowngrade4Resok(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
