/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of the PUTFH operation in NFSv4 protocol.
    /// </summary>
    public class Putfh4Res : XdrAble
    {
        /// <summary>
        /// The status code indicating the success or failure of the PUTFH operation.
        /// </summary>
        public int Status;

        /// <summary>
        /// Initializes a new instance of the <see cref="Putfh4Res"/> class.
        /// </summary>
        public Putfh4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Putfh4Res"/> class by deserializing from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public Putfh4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this object to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Status);
        }

        /// <summary>
        /// Decodes this object from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Status = xdr.XdrDecodeInt();
        }
    }
}
