/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents quality of protection in NFSv4 protocol.
    /// </summary>
    public class Qop4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the quality of protection value.
        /// </summary>
        public int Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Qop4"/> class.
        /// </summary>
        public Qop4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Qop4"/> class with the specified value.
        /// </summary>
        /// <param name="value">The quality of protection value.</param>
        public Qop4(int value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Qop4"/> class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Qop4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Value);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeInt();
        }
    }
}
