/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result data for the READLINK operation in NFSv4 protocol.
    /// </summary>
    public class Readlink4Resok : XdrAble
    {
        /// <summary>
        /// The symbolic link text content.
        /// </summary>
        public Linktext4 Link;

        /// <summary>
        /// Initializes a new instance of the Readlink4Resok class.
        /// </summary>
        public Readlink4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Readlink4Resok class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Readlink4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the Readlink4Resok instance into the specified XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Link.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the Readlink4Resok instance from the specified XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Link = new Linktext4(xdr);
        }
    }
}
