/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the READDIR operation in NFSv4 protocol.
    /// </summary>
    public class Readdir4Args : XdrAble
    {
        /// <summary>
        /// Cookie value for continuing directory enumeration.
        /// </summary>
        public NfsCookie4 Cookie;

        /// <summary>
        /// Verifier to validate the cookie.
        /// </summary>
        public Verifier4 Cookieverf;

        /// <summary>
        /// Maximum number of bytes of directory information to return.
        /// </summary>
        public Count4 Dircount;

        /// <summary>
        /// Maximum number of bytes for the entire reply.
        /// </summary>
        public Count4 Maxcount;

        /// <summary>
        /// Bitmap specifying which attributes to request for each entry.
        /// </summary>
        public Bitmap4 AttrRequest;

        /// <summary>
        /// Initializes a new instance of the Readdir4Args class.
        /// </summary>
        public Readdir4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Readdir4Args class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Readdir4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the Readdir4Args instance into the specified XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Cookie.XdrEncode(xdr);
            Cookieverf.XdrEncode(xdr);
            Dircount.XdrEncode(xdr);
            Maxcount.XdrEncode(xdr);
            AttrRequest.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the Readdir4Args instance from the specified XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Cookie = new NfsCookie4(xdr);
            Cookieverf = new Verifier4(xdr);
            Dircount = new Count4(xdr);
            Maxcount = new Count4(xdr);
            AttrRequest = new Bitmap4(xdr);
        }
    }
}
