/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result data for the READDIR operation in NFSv4 protocol.
    /// </summary>
    public class Readdir4Resok : XdrAble
    {
        /// <summary>
        /// Cookie verifier for validating subsequent requests.
        /// </summary>
        public Verifier4 Cookieverf;

        /// <summary>
        /// Directory listing containing entries and metadata.
        /// </summary>
        public Dirlist4 Reply;

        /// <summary>
        /// Initializes a new instance of the Readdir4Resok class.
        /// </summary>
        public Readdir4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Readdir4Resok class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Readdir4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the Readdir4Resok instance into the specified XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Cookieverf.XdrEncode(xdr);
            Reply.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the Readdir4Resok instance from the specified XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Cookieverf = new Verifier4(xdr);
            Reply = new Dirlist4(xdr);
        }
    }
}
