/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the RELEASE_LOCKOWNER operation in NFSv4 protocol.
    /// </summary>
    public class ReleaseLockowner4Args : XdrAble
    {
        /// <summary>
        /// The lock owner to be released.
        /// </summary>
        public LockOwner4 LockOwner;

        /// <summary>
        /// Initializes a new instance of the ReleaseLockowner4Args class.
        /// </summary>
        public ReleaseLockowner4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the ReleaseLockowner4Args class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public ReleaseLockowner4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the ReleaseLockowner4Args instance into the specified XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes the ReleaseLockowner4Args instance from the specified XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
