/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of the RELEASE_LOCKOWNER operation in NFSv4 protocol.
    /// </summary>
    public class ReleaseLockowner4Res : XdrAble
    {
        /// <summary>
        /// Status code of the RELEASE_LOCKOWNER operation.
        /// </summary>
        public int Status;

        /// <summary>
        /// Initializes a new instance of the ReleaseLockowner4Res class.
        /// </summary>
        public ReleaseLockowner4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the ReleaseLockowner4Res class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public ReleaseLockowner4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the ReleaseLockowner4Res instance into the specified XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes the ReleaseLockowner4Res instance from the specified XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
