/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the REMOVE operation in NFSv4 protocol.
    /// </summary>
    public class Remove4Args : XdrAble
    {
        /// <summary>
        /// The name of the file or directory to remove.
        /// </summary>
        public Component4 Target;

        /// <summary>
        /// Initializes a new instance of the Remove4Args class.
        /// </summary>
        public Remove4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Remove4Args class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Remove4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the Remove4Args instance into the specified XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Target.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the Remove4Args instance from the specified XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Target = new Component4(xdr);
        }
    }
}
