/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the RENAME operation in NFSv4 protocol.
    /// </summary>
    public class Rename4Args : XdrAble
    {
        /// <summary>
        /// The current name of the file or directory to rename.
        /// </summary>
        public Component4 Oldname;

        /// <summary>
        /// The new name for the file or directory.
        /// </summary>
        public Component4 Newname;

        /// <summary>
        /// Initializes a new instance of the Rename4Args class.
        /// </summary>
        public Rename4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Rename4Args class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Rename4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the Rename4Args instance into the specified XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Oldname.XdrEncode(xdr);
            Newname.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the Rename4Args instance from the specified XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Oldname = new Component4(xdr);
            Newname = new Component4(xdr);
        }
    }
}
