/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for the RENEW operation in NFSv4 protocol.
    /// </summary>
    public class Renew4Args : XdrAble
    {
        /// <summary>
        /// The client identifier to renew the lease for.
        /// </summary>
        public Clientid4 Clientid;

        /// <summary>
        /// Initializes a new instance of the Renew4Args class.
        /// </summary>
        public Renew4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Renew4Args class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public Renew4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the Renew4Args instance into the specified XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes the Renew4Args instance from the specified XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
