/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /// <summary>
    /// Enumeration (collection of constants) for RPC GSS service types.
    /// </summary>
    public class RpcGssSvcT
    {
        /// <summary>
        /// No security service (authentication only).
        /// </summary>
        public const int RPC_GSS_SVC_NONE = 1;

        /// <summary>
        /// Integrity protection (data integrity verification).
        /// </summary>
        public const int RPC_GSS_SVC_INTEGRITY = 2;

        /// <summary>
        /// Privacy protection (data encryption and integrity).
        /// </summary>
        public const int RPC_GSS_SVC_PRIVACY = 3;
    }
}
