/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for a SECINFO_NO_NAME operation in NFSv4 protocol.
    /// </summary>
    public class SecinfoNoName4Args : XdrAble
    {
        /// <summary>
        /// The style of security information to query.
        /// </summary>
        public int Value;

        /// <summary>
        /// Initializes a new instance of the SecinfoNoName4Args class.
        /// </summary>
        public SecinfoNoName4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the SecinfoNoName4Args class with the specified value.
        /// </summary>
        /// <param name="value">The security information style.</param>
        public SecinfoNoName4Args(int value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the SecinfoNoName4Args class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public SecinfoNoName4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this SecinfoNoName4Args instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Value);
        }

        /// <summary>
        /// Decodes this SecinfoNoName4Args instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = xdr.XdrDecodeInt();
        }
    }
}
