/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents security information in NFSv4 protocol.
    /// </summary>
    public class Secinfo4 : XdrAble
    {
        /// <summary>
        /// The security flavor type.
        /// </summary>
        public int Flavor;

        /// <summary>
        /// Additional security information for RPCSEC_GSS flavor.
        /// </summary>
        public RpcsecGssInfo FlavorInfo;

        /// <summary>
        /// Initializes a new instance of the Secinfo4 class.
        /// </summary>
        public Secinfo4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Secinfo4 class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Secinfo4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Secinfo4 instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Flavor);
            switch (Flavor)
            {
                case AuthFlavor.RPCSEC_GSS:
                    FlavorInfo.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes this Secinfo4 instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Flavor = xdr.XdrDecodeInt();
            switch (Flavor)
            {
                case AuthFlavor.RPCSEC_GSS:
                    FlavorInfo = new RpcsecGssInfo(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
