/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for a SECINFO operation in NFSv4 protocol.
    /// </summary>
    public class Secinfo4Args : XdrAble
    {
        /// <summary>
        /// The name of the file or directory to query for security information.
        /// </summary>
        public Component4 Name;

        /// <summary>
        /// Initializes a new instance of the Secinfo4Args class.
        /// </summary>
        public Secinfo4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Secinfo4Args class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Secinfo4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Secinfo4Args instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes this Secinfo4Args instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
