/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /// <summary>
    /// Enumeration (collection of constants) for security info styles.
    /// </summary>
    public class SecinfoStyle4
    {
        /// <summary>
        /// Security information applies to the current file handle.
        /// </summary>
        public const int SECINFO_STYLE4_CURRENT_FH = 0;

        /// <summary>
        /// Security information applies to the parent directory.
        /// </summary>
        public const int SECINFO_STYLE4_PARENT = 1;
    }
}
