/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of a SECINFO_NO_NAME operation in NFSv4 protocol.
    /// </summary>
    public class SecinfoNoName4Res : XdrAble
    {
        /// <summary>
        /// The security information result.
        /// </summary>
        public Secinfo4Res Value;

        /// <summary>
        /// Initializes a new instance of the SecinfoNoName4Res class.
        /// </summary>
        public SecinfoNoName4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the SecinfoNoName4Res class with the specified value.
        /// </summary>
        /// <param name="value">The security information result.</param>
        public SecinfoNoName4Res(Secinfo4Res value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the SecinfoNoName4Res class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public SecinfoNoName4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this SecinfoNoName4Res instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this SecinfoNoName4Res instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new Secinfo4Res(xdr);
        }
    }
}
