/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of a SEQUENCE operation in NFSv4 protocol.
    /// </summary>
    public class Sequence4Res : XdrAble
    {
        /// <summary>
        /// The status of the SEQUENCE operation.
        /// </summary>
        public int SrStatus;

        /// <summary>
        /// The successful result data, populated when status is NFS4_OK.
        /// </summary>
        public Sequence4Resok SrResok4;

        /// <summary>
        /// Initializes a new instance of the Sequence4Res class.
        /// </summary>
        public Sequence4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Sequence4Res class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Sequence4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Sequence4Res instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(SrStatus);
            switch (SrStatus)
            {
                case Nfsstat4.NFS4_OK:
                    SrResok4.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes this Sequence4Res instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            SrStatus = xdr.XdrDecodeInt();
            switch (SrStatus)
            {
                case Nfsstat4.NFS4_OK:
                    SrResok4 = new Sequence4Resok(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
