/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents server owner information in NFSv4 protocol.
    /// </summary>
    public class ServerOwner4 : XdrAble
    {
        /// <summary>
        /// The minor identifier of the server owner.
        /// </summary>
        public Uint64T SoMinorId;

        /// <summary>
        /// The major identifier of the server owner.
        /// </summary>
        public byte[] SoMajorId;

        /// <summary>
        /// Initializes a new instance of the ServerOwner4 class.
        /// </summary>
        public ServerOwner4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the ServerOwner4 class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public ServerOwner4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this ServerOwner4 instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            SoMinorId.XdrEncode(xdr);
            xdr.XdrEncodeDynamicOpaque(SoMajorId);
        }

        /// <summary>
        /// Decodes this ServerOwner4 instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            SoMinorId = new Uint64T(xdr);
            SoMajorId = xdr.XdrDecodeDynamicOpaque();
        }
    }
}
