/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of a SETATTR operation in NFSv4 protocol.
    /// </summary>
    public class Setattr4Res : XdrAble
    {
        /// <summary>
        /// The status of the SETATTR operation.
        /// </summary>
        public int Status;

        /// <summary>
        /// Bitmap indicating which attributes were successfully set.
        /// </summary>
        public Bitmap4 Attrsset;

        /// <summary>
        /// Initializes a new instance of the Setattr4Res class.
        /// </summary>
        public Setattr4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Setattr4Res class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Setattr4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Setattr4Res instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Attrsset.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this Setattr4Res instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Attrsset = new Bitmap4(xdr);
        }
    }
}
