/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result data for a SETCLIENTID operation in NFSv4 protocol.
    /// </summary>
    public class Setclientid4Resok : XdrAble
    {
        /// <summary>
        /// The client identifier assigned by the server.
        /// </summary>
        public Clientid4 Clientid;

        /// <summary>
        /// The verifier for confirming the client ID.
        /// </summary>
        public Verifier4 SetclientidConfirm;

        /// <summary>
        /// Initializes a new instance of the Setclientid4Resok class.
        /// </summary>
        public Setclientid4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Setclientid4Resok class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Setclientid4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Setclientid4Resok instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            SetclientidConfirm.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this Setclientid4Resok instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            SetclientidConfirm = new Verifier4(xdr);
        }
    }
}
