/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result data for a SET_SSV operation in NFSv4 protocol.
    /// </summary>
    public class SetSsv4Resok : XdrAble
    {
        /// <summary>
        /// The digest returned from the SET_SSV operation.
        /// </summary>
        public byte[] SsrDigest;

        /// <summary>
        /// Initializes a new instance of the SetSsv4Resok class.
        /// </summary>
        public SetSsv4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the SetSsv4Resok class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public SetSsv4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this SetSsv4Resok instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes this SetSsv4Resok instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
