/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of a SET_SSV operation in NFSv4 protocol.
    /// </summary>
    public class SetSsv4Res : XdrAble
    {
        /// <summary>
        /// The status of the SET_SSV operation.
        /// </summary>
        public int SsrStatus;

        /// <summary>
        /// The successful result data, populated when status is NFS4_OK.
        /// </summary>
        public SetSsv4Resok SsrResok4;

        /// <summary>
        /// Initializes a new instance of the SetSsv4Res class.
        /// </summary>
        public SetSsv4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the SetSsv4Res class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public SetSsv4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this SetSsv4Res instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(SsrStatus);
            switch (SsrStatus)
            {
                case Nfsstat4.NFS4_OK:
                    SsrResok4.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes this SetSsv4Res instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            SsrStatus = xdr.XdrDecodeInt();
            switch (SsrStatus)
            {
                case Nfsstat4.NFS4_OK:
                    SsrResok4 = new SetSsv4Resok(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
