/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a slot ID in NFSv4 protocol.
    /// </summary>
    public class Slotid4 : XdrAble
    {
        /// <summary>
        /// The slot identifier value used in NFSv4.1 sessions for request ordering and slot management.
        /// </summary>
        public Uint32T Value;

        /// <summary>
        /// Initializes a new instance of the Slotid4 class.
        /// </summary>
        public Slotid4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Slotid4 class with the specified value.
        /// </summary>
        /// <param name="value">The slot ID value.</param>
        public Slotid4(Uint32T value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the Slotid4 class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Slotid4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Slotid4 instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this Slotid4 instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new Uint32T(xdr);
        }
    }
}
