/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents SSR digest input in NFSv4 protocol.
    /// </summary>
    public class SsrDigestInput4 : XdrAble
    {
        /// <summary>
        /// The SEQUENCE operation result for SSR digest input.
        /// </summary>
        public Sequence4Res Sdi_seqres;

        /// <summary>
        /// Initializes a new instance of the SsrDigestInput4 class.
        /// </summary>
        public SsrDigestInput4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the SsrDigestInput4 class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public SsrDigestInput4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this SsrDigestInput4 instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes this SsrDigestInput4 instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
