/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents SSV protection information in NFSv4 protocol.
    /// </summary>
    public class SsvProtInfo4 : XdrAble
    {
        /// <summary>
        /// The state protection operations.
        /// </summary>
        public StateProtectOps4 Spi_ops;

        /// <summary>
        /// The hash algorithm identifier.
        /// </summary>
        public int Spi_hash_alg;

        /// <summary>
        /// The encryption algorithm identifier.
        /// </summary>
        public int Spi_encr_alg;

        /// <summary>
        /// The SSV length.
        /// </summary>
        public int Spi_ssv_len;

        /// <summary>
        /// The replay protection window size.
        /// </summary>
        public int Spi_window;

        /// <summary>
        /// Array of GSS handles for security.
        /// </summary>
        public Gsshandle4T[] spi_handles;

        /// <summary>
        /// Initializes a new instance of the SsvProtInfo4 class.
        /// </summary>
        public SsvProtInfo4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the SsvProtInfo4 class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public SsvProtInfo4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this SsvProtInfo4 instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Spi_hash_alg);
            xdr.XdrEncodeInt(Spi_encr_alg);
            xdr.XdrEncodeInt(Spi_ssv_len);
            xdr.XdrEncodeInt(Spi_window);
            int size = spi_handles.Length;
            xdr.XdrEncodeInt(size);
            for (int idx = 0; idx < size; ++idx)
            {
                spi_handles[idx].XdrEncode(xdr);
            }
        }

        /// <summary>
        /// Decodes this SsvProtInfo4 instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Spi_hash_alg = xdr.XdrDecodeInt();
            Spi_encr_alg = xdr.XdrDecodeInt();
            Spi_ssv_len = xdr.XdrDecodeInt();
            Spi_window = xdr.XdrDecodeInt();
            int size = xdr.XdrDecodeInt();
            spi_handles = new Gsshandle4T[size];
            for (int idx = 0; idx < size; ++idx)
            {
                spi_handles[idx] = new Gsshandle4T(xdr);
            }
        }
    }
}
