/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /// <summary>
    /// Enumeration (collection of constants) for SSV subkey types.
    /// </summary>
    public class SsvSubkey4
    {
        /// <summary>
        /// MIC (Message Integrity Code) subkey for initiator-to-target direction.
        /// </summary>
        public const int SSV4_SUBKEY_MIC_I2T = 1;

        /// <summary>
        /// MIC (Message Integrity Code) subkey for target-to-initiator direction.
        /// </summary>
        public const int SSV4_SUBKEY_MIC_T2I = 2;

        /// <summary>
        /// SEAL (encryption) subkey for initiator-to-target direction.
        /// </summary>
        public const int SSV4_SUBKEY_SEAL_I2T = 3;

        /// <summary>
        /// SEAL (encryption) subkey for target-to-initiator direction.
        /// </summary>
        public const int SSV4_SUBKEY_SEAL_T2I = 4;
    }
}
