/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents state protection arguments in NFSv4 protocol.
    /// </summary>
    public class StateProtect4A : XdrAble
    {
        /// <summary>
        /// The state protection method.
        /// </summary>
        public int Spa_how;

        /// <summary>
        /// Machine credentials state protection operations.
        /// </summary>
        public StateProtectOps4 Spa_mach_ops;

        /// <summary>
        /// SSV state protection parameters.
        /// </summary>
        public SsvSpParms4 Spa_ssv_parms;

        /// <summary>
        /// Initializes a new instance of the StateProtect4A class.
        /// </summary>
        public StateProtect4A()
        {
        }

        /// <summary>
        /// Initializes a new instance of the StateProtect4A class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public StateProtect4A(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this StateProtect4A instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Spa_how);
            switch (Spa_how)
            {
                case StateProtectHow4.SP4_NONE:
                    break;

                case StateProtectHow4.SP4_MACH_CRED:
                    Spa_mach_ops.XdrEncode(xdr);
                    break;

                case StateProtectHow4.SP4_SSV:
                    Spa_ssv_parms.XdrEncode(xdr);
                    break;
            }
        }

        /// <summary>
        /// Decodes this StateProtect4A instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Spa_how = xdr.XdrDecodeInt();
            switch (Spa_how)
            {
                case StateProtectHow4.SP4_NONE:
                    break;

                case StateProtectHow4.SP4_MACH_CRED:
                    Spa_mach_ops = new StateProtectOps4(xdr);
                    break;

                case StateProtectHow4.SP4_SSV:
                    Spa_ssv_parms = new SsvSpParms4(xdr);
                    break;
            }
        }
    }
}
