/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents state protection results in NFSv4 protocol.
    /// </summary>
    public class StateProtect4R : XdrAble
    {
        /// <summary>
        /// The state protection method.
        /// </summary>
        public int Spr_how;

        /// <summary>
        /// Machine credentials state protection operations.
        /// </summary>
        public StateProtectOps4 Spr_mach_ops;

        /// <summary>
        /// SSV protection information.
        /// </summary>
        public SsvProtInfo4 Spr_ssv_info;

        /// <summary>
        /// Initializes a new instance of the StateProtect4R class.
        /// </summary>
        public StateProtect4R()
        {
        }

        /// <summary>
        /// Initializes a new instance of the StateProtect4R class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public StateProtect4R(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this StateProtect4R instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Spr_how);
            switch (Spr_how)
            {
                case StateProtectHow4.SP4_NONE:
                    break;

                case StateProtectHow4.SP4_MACH_CRED:
                    Spr_mach_ops.XdrEncode(xdr);
                    break;

                case StateProtectHow4.SP4_SSV:
                    Spr_ssv_info.XdrEncode(xdr);
                    break;
            }
        }

        /// <summary>
        /// Decodes this StateProtect4R instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Spr_how = xdr.XdrDecodeInt();
            switch (Spr_how)
            {
                case StateProtectHow4.SP4_NONE:
                    break;

                case StateProtectHow4.SP4_MACH_CRED:
                    Spr_mach_ops = new StateProtectOps4(xdr);
                    break;

                case StateProtectHow4.SP4_SSV:
                    Spr_ssv_info = new SsvProtInfo4(xdr);
                    break;
            }
        }
    }
}
