/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /// <summary>
    /// Enumeration (collection of constants) for state protection methods.
    /// </summary>
    public class StateProtectHow4
    {
        /// <summary>
        /// No state protection.
        /// </summary>
        public const int SP4_NONE = 0;

        /// <summary>
        /// Machine credential based state protection.
        /// </summary>
        public const int SP4_MACH_CRED = 1;

        /// <summary>
        /// SSV (Secret State Verifier) based state protection.
        /// </summary>
        public const int SP4_SSV = 2;
    }
}
