/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents threshold write I/O size in NFSv4 protocol.
    /// </summary>
    public class Threshold4WriteIosize : XdrAble
    {
        /// <summary>
        /// The threshold write I/O size Value.
        /// </summary>
        public Length4 Value;

        /// <summary>
        /// Initializes a new instance of the Threshold4WriteIosize class.
        /// </summary>
        public Threshold4WriteIosize()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Threshold4WriteIosize class with the specified Value.
        /// </summary>
        /// <param name="Value">The threshold write I/O size.</param>
        public Threshold4WriteIosize(Length4 Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the Threshold4WriteIosize class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Threshold4WriteIosize(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Threshold4WriteIosize instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this Threshold4WriteIosize instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new Length4(xdr);
        }
    }
}
