/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a case-insensitive UTF-8 string in NFSv4 protocol.
    /// </summary>
    public class Utf8strCis : XdrAble
    {
        /// <summary>
        /// The case-insensitive UTF-8 string Value.
        /// </summary>
        public Utf8string Value;

        /// <summary>
        /// Initializes a new instance of the Utf8strCis class.
        /// </summary>
        public Utf8strCis()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Utf8strCis class with the specified Value.
        /// </summary>
        /// <param name="Value">The case-insensitive UTF-8 string.</param>
        public Utf8strCis(Utf8string Value)
        {
            this.Value = Value;
        }

        /// <summary>
        /// Initializes a new instance of the Utf8strCis class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Utf8strCis(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Utf8strCis instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this Utf8strCis instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new Utf8string(xdr);
        }
    }
}
