/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result of a VERIFY operation in NFSv4 protocol.
    /// </summary>
    public class Verify4Res : XdrAble
    {
        /// <summary>
        /// The status of the VERIFY operation.
        /// </summary>
        public int Status;

        /// <summary>
        /// Initializes a new instance of the Verify4Res class.
        /// </summary>
        public Verify4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Verify4Res class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Verify4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Verify4Res instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes this Verify4Res instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
