/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for a VERIFY operation in NFSv4 protocol.
    /// </summary>
    public class Verify4Args : XdrAble
    {
        /// <summary>
        /// The attributes to verify against the object.
        /// </summary>
        public Fattr4 ObjAttributes;

        /// <summary>
        /// Initializes a new instance of the Verify4Args class.
        /// </summary>
        public Verify4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Verify4Args class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Verify4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Verify4Args instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes this Verify4Args instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
