/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    /// <summary>
    /// Enumeration (collection of constants) for reasons why delegation was not granted.
    /// </summary>
    public class WhyNoDelegation4
    {
        /// <summary>
        /// Client did not want delegation.
        /// </summary>
        public const int WND4_NOT_WANTED = 0;

        /// <summary>
        /// Delegation not granted due to resource contention.
        /// </summary>
        public const int WND4_CONTENTION = 1;

        /// <summary>
        /// Server lacks resources to grant delegation.
        /// </summary>
        public const int WND4_RESOURCE = 2;

        /// <summary>
        /// Delegation not supported for this file type.
        /// </summary>
        public const int WND4_NOT_SUPP_FTYPE = 3;

        /// <summary>
        /// Write delegation not supported for this file type.
        /// </summary>
        public const int WND4_WRITE_DELEG_NOT_SUPP_FTYPE = 4;

        /// <summary>
        /// Delegation upgrade not supported.
        /// </summary>
        public const int WND4_NOT_SUPP_UPGRADE = 5;

        /// <summary>
        /// Delegation downgrade not supported.
        /// </summary>
        public const int WND4_NOT_SUPP_DOWNGRADE = 6;

        /// <summary>
        /// Delegation was cancelled.
        /// </summary>
        public const int WND4_CANCELLED = 7;

        /// <summary>
        /// Target is a directory (delegations not granted for directories).
        /// </summary>
        public const int WND4_IS_DIR = 8;
    }
}
