/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for a WRITE operation in NFSv4 protocol.
    /// </summary>
    public class Write4Args : XdrAble
    {
        /// <summary>
        /// The state identifier for the file.
        /// </summary>
        public Stateid4 Stateid;

        /// <summary>
        /// The offset at which to begin writing data.
        /// </summary>
        public Offset4 Offset;

        /// <summary>
        /// The stable storage parameter indicating write commitment level.
        /// </summary>
        public int Stable;

        /// <summary>
        /// The data to write to the file.
        /// </summary>
        public byte[] Data;

        /// <summary>
        /// Initializes a new instance of the Write4Args class.
        /// </summary>
        public Write4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Write4Args class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Write4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Write4Args instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Stateid.XdrEncode(xdr);
            Offset.XdrEncode(xdr);
            xdr.XdrEncodeInt(Stable);
            xdr.XdrEncodeDynamicOpaque(Data);
        }

        /// <summary>
        /// Decodes this Write4Args instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Stateid = new Stateid4(xdr);
            Offset = new Offset4(xdr);
            Stable = xdr.XdrDecodeInt();
            Data = xdr.XdrDecodeDynamicOpaque();
        }
    }
}
