/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the successful result data for a WRITE operation in NFSv4 protocol.
    /// </summary>
    public class Write4Resok : XdrAble
    {
        /// <summary>
        /// The number of bytes written.
        /// </summary>
        public Count4 Count;

        /// <summary>
        /// The committed parameter indicating the level of commitment to stable storage.
        /// </summary>
        public int Committed;

        /// <summary>
        /// The write verifier used to detect server reboot between unstable writes and COMMIT.
        /// </summary>
        public Verifier4 Writeverf;

        /// <summary>
        /// Initializes a new instance of the Write4Resok class.
        /// </summary>
        public Write4Resok()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Write4Resok class by decoding from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public Write4Resok(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes this Write4Resok instance to the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to encode to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Count.XdrEncode(xdr);
            xdr.XdrEncodeInt(Committed);
            Writeverf.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this Write4Resok instance from the specified XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR stream to decode from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Count = new Count4(xdr);
            Committed = xdr.XdrDecodeInt();
            Writeverf = new Verifier4(xdr);
        }
    }
}
