/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.Commons
{
    using NFSLibrary.Rpc;
    /// <summary>
    /// Represents a node in the linked list of NFS exports (shares) available on the server.
    /// </summary>
    public class ExportNode : XdrAble
    {
        private Name _Mountpath;
        private Groups _Exgroups;
        private Exports _Next;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExportNode"/> class.
        /// </summary>
        public ExportNode()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExportNode"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public ExportNode(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this export node to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._Mountpath.XdrEncode(xdr);
            this._Exgroups.XdrEncode(xdr);
            this._Next.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this export node from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Mountpath = new Name(xdr);
            this._Exgroups = new Groups(xdr);
            this._Next = new Exports(xdr);
        }

        /// <summary>
        /// Gets the mount path for this export.
        /// </summary>
        public Name MountPath
        {
            get
            { return this._Mountpath; }
        }

        /// <summary>
        /// Gets the groups allowed to access this export.
        /// </summary>
        public Groups ExportGroups
        {
            get
            { return this._Exgroups; }
        }

        /// <summary>
        /// Gets the next export in the linked list.
        /// </summary>
        public Exports Next
        {
            get
            { return this._Next; }
        }
    }
}
