/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.Commons
{
    using NFSLibrary.Rpc;
    using System;
    /// <summary>
    /// Represents a name string used in NFS protocol operations (file names, directory names, etc.).
    /// </summary>
    public class Name : XdrAble
    {
        private String _Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="Name"/> class.
        /// </summary>
        public Name()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="Name"/> class with the specified value.
        /// </summary>
        /// <param name="value">The name string value.</param>
        public Name(String value)
        { this._Value = value; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Name"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public Name(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this name to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        { xdr.XdrEncodeString(this._Value); }

        /// <summary>
        /// Decodes this name from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        { this._Value = xdr.XdrDecodeString(); }

        /// <summary>
        /// Gets or sets the name string value.
        /// </summary>
        public String Value
        {
            get
            { return this._Value; }
            set
            { this._Value = value; }
        }
    }

    // End of filename.cs
}