/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.Commons
{
    using System;
    /// <summary>
    /// Represents the attributes of an NFS file or directory.
    /// </summary>
    public class NFSAttributes
    {
        private DateTime _CDateTime;
        private DateTime _ADateTime;
        private DateTime _MDateTime;
        private NFSItemTypes _Type;
        private NFSPermission _Mode;
        private long _Size;
        private Byte[] _Handle;
        /// <summary>
        /// Initializes a new instance of the <see cref="NFSAttributes"/> class.
        /// </summary>
        /// <param name="cdateTime">The creation time as Unix timestamp (seconds since epoch).</param>
        /// <param name="adateTime">The last access time as Unix timestamp (seconds since epoch).</param>
        /// <param name="mdateTime">The last modification time as Unix timestamp (seconds since epoch).</param>
        /// <param name="type">The type of the NFS item.</param>
        /// <param name="mode">The permission mode of the item.</param>
        /// <param name="size">The size of the item in bytes.</param>
        /// <param name="handle">The NFS file handle.</param>
        public NFSAttributes(int cdateTime, int adateTime, int mdateTime, NFSItemTypes type, NFSPermission mode, long size, byte[] handle)
        {
            this._CDateTime = new System.DateTime(1970, 1, 1).AddSeconds(cdateTime);
            this._ADateTime = new System.DateTime(1970, 1, 1).AddSeconds(adateTime);
            this._MDateTime = new System.DateTime(1970, 1, 1).AddSeconds(mdateTime);
            this._Type = type;
            this._Size = size;
            this._Mode = mode;
            this._Handle = (Byte[])handle.Clone();
        }

        /// <summary>
        /// Gets the creation date and time of the item.
        /// </summary>
        public DateTime CreateDateTime
        {
            get
            { return this._CDateTime; }
        }

        /// <summary>
        /// Gets the last access date and time of the item.
        /// </summary>
        public DateTime LastAccessedDateTime
        {
            get
            { return this._ADateTime; }
        }

        /// <summary>
        /// Gets the last modification date and time of the item.
        /// </summary>
        public DateTime ModifiedDateTime
        {
            get
            { return this._MDateTime; }
        }

        /// <summary>
        /// Gets the type of the NFS item (file, directory, etc.).
        /// </summary>
        public NFSItemTypes NFSType
        {
            get
            { return this._Type; }
        }

        /// <summary>
        /// Gets the permission mode of the item.
        /// </summary>
        public NFSPermission Mode
        {
            get
            { return this._Mode; }
        }

        /// <summary>
        /// Gets the size of the item in bytes.
        /// </summary>
        public long Size
        {
            get
            { return this._Size; }
        }

        /// <summary>
        /// Gets the NFS file handle for this item.
        /// </summary>
        public Byte[] Handle
        {
            get
            { return this._Handle; }
        }

        /// <summary>
        /// Returns a string representation of the NFS attributes.
        /// </summary>
        /// <returns>A string containing all attribute values.</returns>
        public override string ToString()
        {
            System.Text.StringBuilder HandleString = new System.Text.StringBuilder();

            for (int bC = 0; bC < Handle.Length; bC++)
            { HandleString.Append(((Byte)Handle.GetValue(bC)).ToString("X")); }

            return
                $"CDateTime: {CreateDateTime}, ADateTime: {LastAccessedDateTime}, MDateTime: {ModifiedDateTime}, Type: {NFSType}, Mode: {Mode.UserAccess}{Mode.GroupAccess}{Mode.OtherAccess}, Size: {Size}, Handle: {HandleString}";
        }
    }
}