/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.Commons
{
    /// <summary>
    /// NFS mount status codes returned by mount operations.
    /// </summary>
    public enum NFSMountStats
    {
        /// <summary>No error.</summary>
        MNT_OK = 0,
        /// <summary>Not owner.</summary>
        MNTERR_PERM = 1,
        /// <summary>No such file or directory.</summary>
        MNTERR_NOENT = 2,
        /// <summary>No such process.</summary>
        MNTERR_SRCH = 3,
        /// <summary>Interrupted system call.</summary>
        MNTERR_INTR = 4,
        /// <summary>I/O error.</summary>
        MNTERR_IO = 5,
        /// <summary>No such device or address.</summary>
        MNTERR_NXIO = 6,
        /// <summary>Argument list too long.</summary>
        MNTERR_TOOBIG = 7,
        /// <summary>Exec format error.</summary>
        MNTERR_NOEXEC = 8,
        /// <summary>Bad file number.</summary>
        MNTERR_BADF = 9,
        /// <summary>No child processes.</summary>
        MNTERR_CHILD = 10,
        /// <summary>Try again (Linux), No more processes (SCO Unix).</summary>
        MNTERR_AGAIN = 11,
        /// <summary>Out of memory (Linux), Not enough space (SCO Unix).</summary>
        MNTERR_NOMEM = 12,
        /// <summary>Permission denied.</summary>
        MNTERR_ACCES = 13,
        /// <summary>Bad address.</summary>
        MNTERR_FAULT = 14,
        /// <summary>Block device required.</summary>
        MNTERR_NOTBLK = 15,
        /// <summary>Device or resource busy.</summary>
        MNTERR_BUSY = 16,
        /// <summary>File exists.</summary>
        MNTERR_EXIST = 17,
        /// <summary>Cross-device link.</summary>
        MNTERR_XDEV = 18,
        /// <summary>No such device.</summary>
        MNTERR_NODEV = 19,
        /// <summary>Not a directory.</summary>
        MNTERR_NOTDIR = 20,
        /// <summary>Is a directory.</summary>
        MNTERR_ISDIR = 21,
        /// <summary>Invalid argument.</summary>
        MNTERR_INVAL = 22,
        /// <summary>File table overflow.</summary>
        MNTERR_NFILE = 23,
        /// <summary>Too many open files.</summary>
        MNTERR_MFILE = 24,
        /// <summary>Not a typewriter.</summary>
        MNTERR_NOTTY = 25,
        /// <summary>Text file busy.</summary>
        MNTERR_TXTBSY = 26,
        /// <summary>File too large.</summary>
        MNTERR_FBIG = 27,
        /// <summary>No space left on device.</summary>
        MNTERR_NOSPC = 28,
        /// <summary>Illegal seek.</summary>
        MNTERR_SPIPE = 29,
        /// <summary>Read-only file system.</summary>
        MNTERR_ROFS = 30,
        /// <summary>Too many links.</summary>
        MNTERR_MLINK = 31,
        /// <summary>Broken pipe.</summary>
        MNTERR_PIPE = 32,
        /// <summary>Filename too long.</summary>
        MNTERR_NAMETOOLONG = 63,
        /// <summary>Operation not supported.</summary>
        MNTERR_NOTSUPP = 10004,
        /// <summary>A failure on the server.</summary>
        MNTERR_SERVERFAULT = 10006
    }
}
