/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.Commons
{
    /// <summary>
    /// Represents Unix-style file permissions (read/write/execute for user/group/other).
    /// </summary>
    public class NFSPermission
    {
        private byte _User;
        private byte _Group;
        private byte _Other;

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSPermission"/> class with no permissions set.
        /// </summary>
        public NFSPermission()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSPermission"/> class with the specified permissions.
        /// </summary>
        /// <param name="UserAccess">The user (owner) permission bits (0-7).</param>
        /// <param name="GroupAccess">The group permission bits (0-7).</param>
        /// <param name="OtherAccess">The other (world) permission bits (0-7).</param>
        public NFSPermission(byte UserAccess, byte GroupAccess, byte OtherAccess)
        {
            this._User = UserAccess;
            this._Group = GroupAccess;
            this._Other = OtherAccess;
        }

        /// <summary>
        /// Gets or sets the user (owner) permission bits.
        /// </summary>
        /// <remarks>
        /// Values: 0=none, 1=execute, 2=write, 3=write+execute, 4=read, 5=read+execute, 6=read+write, 7=all.
        /// </remarks>
        public byte UserAccess
        {
            get
            { return this._User; }
            set
            { this._User = value; }
        }

        /// <summary>
        /// Gets or sets the group permission bits.
        /// </summary>
        /// <remarks>
        /// Values: 0=none, 1=execute, 2=write, 3=write+execute, 4=read, 5=read+execute, 6=read+write, 7=all.
        /// </remarks>
        public byte GroupAccess
        {
            get
            { return this._Group; }
            set
            { this._Group = value; }
        }

        /// <summary>
        /// Gets or sets the other (world) permission bits.
        /// </summary>
        /// <remarks>
        /// Values: 0=none, 1=execute, 2=write, 3=write+execute, 4=read, 5=read+execute, 6=read+write, 7=all.
        /// </remarks>
        public byte OtherAccess
        {
            get
            { return this._Other; }
            set
            { this._Other = value; }
        }

        /// <summary>
        /// Gets or sets the permission mode as an octal integer (e.g., 755, 644).
        /// </summary>
        /// <remarks>
        /// Returns -1 if all permission bytes are 0xff (unset).
        /// </remarks>
        public int Mode
        {
            get
            {
                if (_User == 0xff && _Group == 0xff && _Other == 0xff)
                    return -1;
                /* Calculate Permission */
                return
                    (((int)this._User) << 6) | (((int)this._Group) << 3) | ((int)this._Other);
                /*  ---  */
            }
            set
            {
                int tUser = value, tGroup = value, tOther = value;

                this._User = (byte)((tUser >> 6) & 0x7);
                this._Group = (byte)((tGroup >> 3) & 0x7);
                this._Other = (byte)(tOther & 0x7);
            }
        }

        /// <summary>
        /// Returns a string representation of the permissions in rwx format.
        /// </summary>
        /// <returns>A string showing user, group, and other permissions separated by " | ".</returns>
        public override string ToString()
        {
            return CalcMode(_User) + " | " + CalcMode(_Group) + " | " + CalcMode(_Other);
        }

        private string CalcMode(byte modfg)
        {
            switch (modfg)
            {
                case 1:
                    return "x";

                case 2:
                    return "w";

                case 3:
                    return "wx";

                case 4:
                    return "r";

                case 5:
                    return "rx";

                case 6:
                    return "rw";

                case 7:
                    return "rwx";

                default:
                    return "";
            }
        }
    }
}