/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.Commons
{
    using NFSLibrary.Rpc;
    /// <summary>
    /// Represents an NFS time value with seconds and microseconds precision.
    /// </summary>
    public class NFSTimeValue : XdrAble
    {
        private int _Seconds;
        private int _Useconds;

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSTimeValue"/> class with unset values (-1).
        /// </summary>
        public NFSTimeValue()
        {
            this._Seconds = -1;
            this._Useconds = -1;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSTimeValue"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public NFSTimeValue(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this time value to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(this._Seconds);
            xdr.XdrEncodeInt(this._Useconds);
        }

        /// <summary>
        /// Decodes this time value from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Seconds = xdr.XdrDecodeInt();
            this._Useconds = xdr.XdrDecodeInt();
        }

        /// <summary>
        /// Gets or sets the seconds component of the time value.
        /// </summary>
        public int Seconds
        {
            get
            { return this._Seconds; }
            set
            { this._Seconds = value; }
        }

        /// <summary>
        /// Gets or sets the microseconds component of the time value.
        /// </summary>
        public int UnixSeconds
        {
            get
            { return this._Useconds; }
            set
            { this._Useconds = value; }
        }
    }

    // End of nfstimeval.cs
}