/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the result for a CB_GETATTR4 callback operation in NFS v4 protocol.
    /// </summary>
    public class CbGetattr4Res : XdrAble
    {
        /// <summary>
        /// Gets or sets the status of the operation.
        /// </summary>
        public int Status;

        /// <summary>
        /// Gets or sets the successful result when status is NFS4_OK.
        /// </summary>
        public CbGetattr4Resok Resok4;

        /// <summary>
        /// Initializes a new instance of the CbGetattr4Res class.
        /// </summary>
        public CbGetattr4Res()
        {
        }

        /// <summary>
        /// Initializes a new instance of the CbGetattr4Res class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public CbGetattr4Res(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(Status);
            switch (Status)
            {
                case Nfsstat4.NFS4_OK:
                    Resok4.XdrEncode(xdr);
                    break;

                default:
                    break;
            }
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Status = xdr.XdrDecodeInt();
            switch (Status)
            {
                case Nfsstat4.NFS4_OK:
                    Resok4 = new CbGetattr4Resok(xdr);
                    break;

                default:
                    break;
            }
        }
    }
}
