/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for a CB_RECALLABLE_OBJ_AVAIL4 callback operation in NFS v4 protocol.
    /// </summary>
    public class CbRecallableObjAvail4Args : XdrAble
    {
        /// <summary>
        /// Gets or sets the recall any arguments value.
        /// </summary>
        public CbRecallAny4Args Value;

        /// <summary>
        /// Initializes a new instance of the CbRecallableObjAvail4Args class.
        /// </summary>
        public CbRecallableObjAvail4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the CbRecallableObjAvail4Args class with a value.
        /// </summary>
        /// <param name="value">The recall any arguments value.</param>
        public CbRecallableObjAvail4Args(CbRecallAny4Args value)
        {
            this.Value = value;
        }

        /// <summary>
        /// Initializes a new instance of the CbRecallableObjAvail4Args class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public CbRecallableObjAvail4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            Value.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            Value = new CbRecallAny4Args(xdr);
        }
    }
}
