/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents the arguments for a CB_WANTS_CANCELLED4 callback operation in NFS v4 protocol.
    /// </summary>
    public class CbWantsCancelled4Args : XdrAble
    {
        /// <summary>
        /// Gets or sets whether contended wants are cancelled.
        /// </summary>
        public bool CwcaContendedWantsCancelled;

        /// <summary>
        /// Gets or sets whether resourced wants are cancelled.
        /// </summary>
        public bool CwcaResourcedWantsCancelled;

        /// <summary>
        /// Initializes a new instance of the CbWantsCancelled4Args class.
        /// </summary>
        public CbWantsCancelled4Args()
        {
        }

        /// <summary>
        /// Initializes a new instance of the CbWantsCancelled4Args class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public CbWantsCancelled4Args(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeBoolean(CwcaResourcedWantsCancelled);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            CwcaResourcedWantsCancelled = xdr.XdrDecodeBoolean();
        }
    }
}
