/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    /// <summary>
    /// Defines layout recall types for NFS v4 protocol callbacks.
    /// </summary>
    public class LayoutrecallType4
    {
        private const int LAYOUT4_RET_REC_FILE = 1;
        private const int LAYOUT4_RET_REC_FSID = 2;
        private const int LAYOUT4_RET_REC_ALL = 3;

        /// <summary>
        /// Recall layout for a specific file.
        /// </summary>
        public const int LAYOUTRECALL4_FILE = LAYOUT4_RET_REC_FILE;

        /// <summary>
        /// Recall layout for a file system.
        /// </summary>
        public const int LAYOUTRECALL4_FSID = LAYOUT4_RET_REC_FSID;

        /// <summary>
        /// Recall all layouts.
        /// </summary>
        public const int LAYOUTRECALL4_ALL = LAYOUT4_RET_REC_ALL;
    }
}
