/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    /// <summary>
    /// Defines constants used by the NFSv4 callback ONC/RPC program.
    /// </summary>
    public class Nfsv4Callback
    {
        /// <summary>
        /// NFS v4 callback program number.
        /// </summary>
        public const int NFS4_CALLBACK = 0x40000000;

        /// <summary>
        /// Type mask for file layout.
        /// </summary>
        public const int RCA4_TYPE_MASK_FILE_LAYOUT = 3;

        /// <summary>
        /// Minimum type mask for other layouts.
        /// </summary>
        public const int RCA4_TYPE_MASK_OTHER_LAYOUT_MIN = 12;

        /// <summary>
        /// Maximum type mask for other layouts.
        /// </summary>
        public const int RCA4_TYPE_MASK_OTHER_LAYOUT_MAX = 15;

        /// <summary>
        /// CB_NULL procedure number.
        /// </summary>
        public const int CB_NULL_1 = 0;

        /// <summary>
        /// Type mask for read data delegation.
        /// </summary>
        public const int RCA4_TYPE_MASK_RDATA_DLG = 0;

        /// <summary>
        /// Minimum type mask for object layout.
        /// </summary>
        public const int RCA4_TYPE_MASK_OBJ_LAYOUT_MIN = 8;

        /// <summary>
        /// Type mask for block layout.
        /// </summary>
        public const int RCA4_TYPE_MASK_BLK_LAYOUT = 4;

        /// <summary>
        /// Type mask for write data delegation.
        /// </summary>
        public const int RCA4_TYPE_MASK_WDATA_DLG = 1;

        /// <summary>
        /// NFS callback version.
        /// </summary>
        public const int NFS_CB = 1;

        /// <summary>
        /// Maximum type mask for object layout.
        /// </summary>
        public const int RCA4_TYPE_MASK_OBJ_LAYOUT_MAX = 9;

        /// <summary>
        /// Type mask for directory delegation.
        /// </summary>
        public const int RCA4_TYPE_MASK_DIR_DLG = 2;

        /// <summary>
        /// CB_COMPOUND procedure number.
        /// </summary>
        public const int CB_COMPOUND_1 = 1;
    }
}
