/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    using NFSLibrary.Protocols.V4.RPC;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a notification device ID change operation for NFS v4 protocol callbacks.
    /// </summary>
    public class NotifyDeviceidChange4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the layout type.
        /// </summary>
        public Layouttype4 NdcLayouttype;

        /// <summary>
        /// Gets or sets the device identifier.
        /// </summary>
        public Deviceid4 NdcDeviceid;

        /// <summary>
        /// Gets or sets whether the change is immediate.
        /// </summary>
        public bool NdcImmediate;

        /// <summary>
        /// Initializes a new instance of the NotifyDeviceidChange4 class.
        /// </summary>
        public NotifyDeviceidChange4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the NotifyDeviceidChange4 class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NotifyDeviceidChange4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            NdcDeviceid.XdrEncode(xdr);
            xdr.XdrEncodeBoolean(NdcImmediate);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            NdcDeviceid = new Deviceid4(xdr);
            NdcImmediate = xdr.XdrDecodeBoolean();
        }
    }
}
