/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a notification verifier for NFS v4 protocol callbacks.
    /// </summary>
    public class NotifyVerifier4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the old cookie verifier.
        /// </summary>
        public Verifier4 NvOldCookieverf;

        /// <summary>
        /// Gets or sets the new cookie verifier.
        /// </summary>
        public Verifier4 NvNewCookieverf;

        /// <summary>
        /// Initializes a new instance of the NotifyVerifier4 class.
        /// </summary>
        public NotifyVerifier4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the NotifyVerifier4 class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NotifyVerifier4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            NvNewCookieverf.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            NvNewCookieverf = new Verifier4(xdr);
        }
    }
}
