/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    /// <summary>
    /// Defines device ID notification types for NFS v4 protocol callbacks.
    /// </summary>
    public class NotifyDeviceidType4
    {
        /// <summary>
        /// Device ID has changed.
        /// </summary>
        public static readonly int NOTIFY_DEVICEID4_CHANGE = 1;

        /// <summary>
        /// Device ID has been deleted.
        /// </summary>
        public static readonly int NOTIFY_DEVICEID4_DELETE = 2;
    }
}
