/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a notification attribute change operation for NFS v4 protocol callbacks.
    /// </summary>
    public class NotifyAttr4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the changed entry.
        /// </summary>
        public NotifyEntry4 NaChangedEntry;

        /// <summary>
        /// Initializes a new instance of the NotifyAttr4 class.
        /// </summary>
        public NotifyAttr4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the NotifyAttr4 class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NotifyAttr4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
        }
    }
}
