/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a notification remove operation for NFS v4 protocol callbacks.
    /// </summary>
    public class NotifyRemove4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the old entry being removed.
        /// </summary>
        public NotifyEntry4 NrmOldEntry;

        /// <summary>
        /// Gets or sets the cookie of the old entry.
        /// </summary>
        public NfsCookie4 NrmOldEntryCookie;

        /// <summary>
        /// Initializes a new instance of the NotifyRemove4 class.
        /// </summary>
        public NotifyRemove4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the NotifyRemove4 class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public NotifyRemove4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            NrmOldEntryCookie.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            NrmOldEntryCookie = new NfsCookie4(xdr);
        }
    }
}
