/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V4.RPC.Callback
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a previous entry reference for NFS v4 protocol callbacks.
    /// </summary>
    public class PrevEntry4 : XdrAble
    {
        /// <summary>
        /// Gets or sets the previous entry.
        /// </summary>
        public NotifyEntry4 PePrevEntry;

        /// <summary>
        /// Gets or sets the cookie of the previous entry.
        /// </summary>
        public NfsCookie4 PePrevEntryCookie;

        /// <summary>
        /// Initializes a new instance of the PrevEntry4 class.
        /// </summary>
        public PrevEntry4()
        {
        }

        /// <summary>
        /// Initializes a new instance of the PrevEntry4 class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public PrevEntry4(XdrDecodingStream xdr)
        {
            XdrDecode(xdr);
        }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            PePrevEntryCookie.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            PePrevEntryCookie = new NfsCookie4(xdr);
        }
    }
}
