/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents arguments for access check operations for NFS v3 protocol operations.
    /// </summary>
    public class AccessArguments : XdrAble
    {
        private NFSHandle _Obj;
        private int _Access;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccessArguments"/> class.
        /// </summary>
        public AccessArguments()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccessArguments"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public AccessArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._Obj.XdrEncode(xdr);
            xdr.XdrEncodeInt(this._Access);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Obj = new NFSHandle();
            this._Obj.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            this._Obj.XdrDecode(xdr);
            this._Access = xdr.XdrDecodeInt();
        }

        /// <summary>
        /// Gets or sets the NFS handle for the file or directory to check access permissions.
        /// </summary>
        public NFSHandle Handle
        {
            get
            { return this._Obj; }
            set
            { this._Obj = value; }
        }

        /// <summary>
        /// Gets or sets the access permissions to check.
        /// </summary>
        public int Access
        {
            get
            { return this._Access; }
            set
            { this._Access = value; }
        }
    }

    // End of ACCESS3args.cs
}