/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents arguments for commit operations for NFS v3 protocol operations.
    /// </summary>
    public class CommitArguments : XdrAble
    {
        private NFSHandle _File;
        private long _Offset;
        private int _Count;

        /// <summary>
        /// Initializes a new instance of the <see cref="CommitArguments"/> class.
        /// </summary>
        public CommitArguments()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommitArguments"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public CommitArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._File.XdrEncode(xdr);
            xdr.XdrEncodeLong(this._Offset);
            xdr.XdrEncodeInt(this._Count);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._File = new NFSHandle();
            this._File.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            this._File.XdrDecode(xdr);
            this._Offset = xdr.XdrDecodeLong();
            this._Count = xdr.XdrDecodeInt();
        }

        /// <summary>
        /// Gets or sets the file handle to commit.
        /// </summary>
        public NFSHandle File
        {
            get
            { return this._File; }
            set
            { this._File = value; }
        }

        /// <summary>
        /// Gets or sets the byte offset in the file where the commit should start.
        /// </summary>
        public long Offset
        {
            get
            { return this._Offset; }
            set
            { this._Offset = value; }
        }

        /// <summary>
        /// Gets or sets the number of bytes to commit.
        /// </summary>
        public int Count
        {
            get
            { return this._Count; }
            set
            { this._Count = value; }
        }
    }

    // End of COMMIT3args.cs
}