/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents device data for character and block special files for NFS v3 protocol operations.
    /// </summary>
    public class DeviceData : XdrAble
    {
        private MakeAttributes _DevAttributes;
        private SpecInformation _Spec;

        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceData"/> class.
        /// </summary>
        public DeviceData()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceData"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public DeviceData(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._DevAttributes.XdrEncode(xdr);
            this._Spec.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._DevAttributes = new MakeAttributes(xdr);
            this._Spec = new SpecInformation(xdr);
        }

        /// <summary>
        /// Gets or sets the attributes for the device.
        /// </summary>
        public MakeAttributes Attributes
        {
            get
            { return this._DevAttributes; }
            set
            { this._DevAttributes = value; }
        }

        /// <summary>
        /// Gets or sets the device specification (major and minor numbers).
        /// </summary>
        public SpecInformation Specifications
        {
            get
            { return this._Spec; }
            set
            { this._Spec = value; }
        }
    }
}
