/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents successful extended directory read data for NFS v3 protocol.
    /// </summary>
    public class ExtendedReadFolderAccessOK : XdrAble
    {
        private PostOperationAttributes _DirAttributes;
        private byte[] _Cookieverf;
        private FolderList _Reply;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtendedReadFolderAccessOK"/> class.
        /// </summary>
        public ExtendedReadFolderAccessOK()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtendedReadFolderAccessOK"/> class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public ExtendedReadFolderAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._DirAttributes.XdrEncode(xdr);
            xdr.XdrEncodeOpaque(this._Cookieverf, NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            this._Reply.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._DirAttributes = new PostOperationAttributes(xdr);
            this._Cookieverf = xdr.XdrDecodeOpaque(NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            this._Reply = new FolderList(xdr);
        }

        /// <summary>
        /// Gets the post-operation attributes of the directory.
        /// </summary>
        public PostOperationAttributes Attributes
        {
            get
            { return this._DirAttributes; }
        }

        /// <summary>
        /// Gets the cookie verifier for the directory read operation.
        /// </summary>
        public byte[] CookieVerification
        {
            get
            { return this._Cookieverf; }
        }

        /// <summary>
        /// Gets the reply containing extended directory entries with attributes.
        /// </summary>
        public FolderList Reply
        {
            get
            { return this._Reply; }
        }
    }
}
