/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents arguments for extended read directory operations (READDIRPLUS) for NFS v3 protocol operations.
    /// </summary>
    public class ExtendedReadFolderArguments : XdrAble
    {
        private NFSHandle _Dir;
        private NFSCookie _Cookie;
        private byte[] _Cookieverf;
        private int _Dircount;
        private int _Maxcount;

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtendedReadFolderArguments"/> class.
        /// </summary>
        public ExtendedReadFolderArguments()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ExtendedReadFolderArguments"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public ExtendedReadFolderArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._Dir.XdrEncode(xdr);
            this._Cookie.XdrEncode(xdr);
            xdr.XdrEncodeOpaque(this._Cookieverf, NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            xdr.XdrEncodeInt(this._Dircount);
            xdr.XdrEncodeInt(this._Maxcount);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Dir = new NFSHandle();
            this._Dir.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            this._Dir.XdrDecode(xdr);
            this._Cookie = new NFSCookie(xdr);
            this._Cookieverf = xdr.XdrDecodeOpaque(NFSv3Protocol.NFS3_COOKIEVERFSIZE);
            this._Dircount = xdr.XdrDecodeInt();
            this._Maxcount = xdr.XdrDecodeInt();
        }

        /// <summary>
        /// Gets or sets the directory handle to read from.
        /// </summary>
        public NFSHandle Directory
        {
            get
            { return this._Dir; }
            set
            { this._Dir = value; }
        }

        /// <summary>
        /// Gets or sets the cookie for resuming directory reads.
        /// </summary>
        public NFSCookie Cookie
        {
            get
            { return this._Cookie; }
            set
            { this._Cookie = value; }
        }

        /// <summary>
        /// Gets or sets the cookie verifier for validating the cookie.
        /// </summary>
        public byte[] CookieVerification
        {
            get
            { return this._Cookieverf; }
            set
            { this._Cookieverf = value; }
        }

        /// <summary>
        /// Gets or sets the maximum size in bytes of directory information.
        /// </summary>
        public int DirectoryLength
        {
            get
            { return this._Dircount; }
            set
            { this._Dircount = value; }
        }

        /// <summary>
        /// Gets or sets the maximum size in bytes of the entire reply.
        /// </summary>
        public int MaximumLength
        {
            get
            { return this._Maxcount; }
            set
            { this._Maxcount = value; }
        }
    }

    // End of READDIRPLUS3args.cs
}