/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents file attributes for NFS v3 protocol operations.
    /// </summary>
    public class FileAttributes : XdrAble
    {
        private NFSItemTypes _Type;
        private NFSPermission _Mode;
        private int _Nlink;
        private int _Uid;
        private int _Gid;
        private long _Size;
        private long _Used;
        private SpecInformation _Rdev;
        private long _Fsid;
        private long _Fileid;
        private NFSTimeValue _Atime;
        private NFSTimeValue _Mtime;
        private NFSTimeValue _Ctime;

        /// <summary>
        /// Initializes a new instance of the <see cref="FileAttributes"/> class.
        /// </summary>
        public FileAttributes()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="FileAttributes"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public FileAttributes(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt((int)this._Type);
            xdr.XdrEncodeInt(this._Mode.Mode);
            xdr.XdrEncodeInt(this._Nlink);
            xdr.XdrEncodeInt(this._Uid);
            xdr.XdrEncodeInt(this._Gid);
            xdr.XdrEncodeLong(this._Size);
            xdr.XdrEncodeLong(this._Used);
            this._Rdev.XdrEncode(xdr);
            xdr.XdrEncodeLong(this._Fsid);
            xdr.XdrEncodeLong(this._Fileid);
            this._Atime.XdrEncode(xdr);
            this._Mtime.XdrEncode(xdr);
            this._Ctime.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Type = (NFSItemTypes)xdr.XdrDecodeInt();

            this._Mode = new NFSPermission();
            this._Mode.Mode = xdr.XdrDecodeInt();

            this._Nlink = xdr.XdrDecodeInt();
            this._Uid = xdr.XdrDecodeInt();
            this._Gid = xdr.XdrDecodeInt();
            this._Size = xdr.XdrDecodeLong();
            this._Used = xdr.XdrDecodeLong();

            this._Rdev = new SpecInformation();
            this._Rdev.XdrDecode(xdr);

            this._Fsid = xdr.XdrDecodeLong();
            this._Fileid = xdr.XdrDecodeLong();
            this._Atime = new NFSTimeValue(xdr);
            this._Mtime = new NFSTimeValue(xdr);
            this._Ctime = new NFSTimeValue(xdr);
        }

        /// <summary>
        /// Gets the type of the file system object (file, directory, symlink, etc.).
        /// </summary>
        public NFSItemTypes Type
        {
            get
            { return this._Type; }
        }

        /// <summary>
        /// Gets the file permission mode.
        /// </summary>
        public NFSPermission Mode
        {
            get
            { return this._Mode; }
        }

        /// <summary>
        /// Gets the number of hard links to the file.
        /// </summary>
        public int Link
        {
            get
            { return this._Nlink; }
        }

        /// <summary>
        /// Gets the user ID of the file owner.
        /// </summary>
        public int UserID
        {
            get
            { return this._Uid; }
        }

        /// <summary>
        /// Gets the group ID of the file owner.
        /// </summary>
        public int GroupID
        {
            get
            { return this._Gid; }
        }

        /// <summary>
        /// Gets the file size in bytes.
        /// </summary>
        public long Size
        {
            get
            { return this._Size; }
        }

        /// <summary>
        /// Gets the disk space used by the file in bytes.
        /// </summary>
        public long Used
        {
            get
            { return this._Used; }
        }

        /// <summary>
        /// Gets the device information for special files.
        /// </summary>
        public SpecInformation BlockInfo
        {
            get
            { return this._Rdev; }
        }

        /// <summary>
        /// Gets the file system identifier.
        /// </summary>
        public long FSID
        {
            get
            { return this._Fsid; }
        }

        /// <summary>
        /// Gets the file identifier within the file system.
        /// </summary>
        public long FileID
        {
            get
            { return this._Fileid; }
        }

        /// <summary>
        /// Gets the last access time.
        /// </summary>
        public NFSTimeValue LastAccessedTime
        {
            get
            { return this._Atime; }
        }

        /// <summary>
        /// Gets the last modification time.
        /// </summary>
        public NFSTimeValue ModifiedTime
        {
            get
            { return this._Mtime; }
        }

        /// <summary>
        /// Gets the creation or metadata change time.
        /// </summary>
        public NFSTimeValue CreateTime
        {
            get
            { return this._Ctime; }
        }
    }

    // End of fattr3.cs
}