/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a folder entry in an extended directory listing for NFS v3 protocol operations.
    /// </summary>
    public class FolderEntry : XdrAble
    {
        private long _Fileid;
        private Name _Name;
        private NFSCookie _Cookie;
        private PostOperationAttributes _NameAttributes;
        private NFSHandle _NameHandle;
        private FolderEntry _Nextentry;

        /// <summary>
        /// Initializes a new instance of the <see cref="FolderEntry"/> class.
        /// </summary>
        public FolderEntry()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="FolderEntry"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public FolderEntry(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            FolderEntry _this = this;

            do
            {
                xdr.XdrEncodeLong(_this._Fileid);
                _this._Name.XdrEncode(xdr);
                _this._Cookie.XdrEncode(xdr);
                _this._NameAttributes.XdrEncode(xdr);
                _this._NameHandle.XdrEncode(xdr);
                _this = _this._Nextentry;
                xdr.XdrEncodeBoolean(_this != null);
            } while (_this != null);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            FolderEntry _this = this;
            FolderEntry _next;

            do
            {
                _this._Fileid = xdr.XdrDecodeLong();
                _this._Name = new Name(xdr);
                _this._Cookie = new NFSCookie(xdr);
                _this._NameAttributes = new PostOperationAttributes(xdr);
                _this._NameHandle = (xdr.XdrDecodeBoolean() ? new NFSHandle(xdr, 3) : null);
                _next = xdr.XdrDecodeBoolean() ? new FolderEntry() : null;
                _this._Nextentry = _next;
                _this = _next;
            } while (_this != null);
        }

        /// <summary>
        /// Gets the file identifier.
        /// </summary>
        public long FileID
        {
            get
            { return this._Fileid; }
        }

        /// <summary>
        /// Gets the file or directory name.
        /// </summary>
        public Name Name
        {
            get
            { return this._Name; }
        }

        /// <summary>
        /// Gets the cookie for resuming directory reads.
        /// </summary>
        public NFSCookie Cookie
        {
            get
            { return this._Cookie; }
        }

        /// <summary>
        /// Gets the post-operation attributes for the entry.
        /// </summary>
        public PostOperationAttributes Attributes
        {
            get
            { return this._NameAttributes; }
        }

        /// <summary>
        /// Gets the file handle for the entry.
        /// </summary>
        public NFSHandle Handle
        {
            get
            { return this._NameHandle; }
        }

        /// <summary>
        /// Gets the next entry in the linked list.
        /// </summary>
        public FolderEntry NextEntry
        {
            get
            { return this._Nextentry; }
        }
    }
}
