/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents successful filesystem information data for NFS v3 protocol.
    /// </summary>
    public class FSInfoAccessOK : XdrAble
    {
        private PostOperationAttributes _ObjAttributes;
        private int _Rtmax;
        private int _Rtpref;
        private int _Rtmult;
        private int _Wtmax;
        private int _Wtpref;
        private int _Wtmult;
        private int _Dtpref;
        private long _Maxfilesize;
        private NFSTimeValue _TimeDelta;
        private int _Properties;

        /// <summary>
        /// Initializes a new instance of the <see cref="FSInfoAccessOK"/> class.
        /// </summary>
        public FSInfoAccessOK()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="FSInfoAccessOK"/> class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public FSInfoAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._ObjAttributes.XdrEncode(xdr);
            xdr.XdrEncodeInt(this._Rtmax);
            xdr.XdrEncodeInt(this._Rtpref);
            xdr.XdrEncodeInt(this._Rtmult);
            xdr.XdrEncodeInt(this._Wtmax);
            xdr.XdrEncodeInt(this._Wtpref);
            xdr.XdrEncodeInt(this._Wtmult);
            xdr.XdrEncodeInt(this._Dtpref);
            xdr.XdrEncodeLong(this._Maxfilesize);
            this._TimeDelta.XdrEncode(xdr);
            xdr.XdrEncodeInt(this._Properties);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._ObjAttributes = new PostOperationAttributes(xdr);
            this._Rtmax = xdr.XdrDecodeInt();
            this._Rtpref = xdr.XdrDecodeInt();
            this._Rtmult = xdr.XdrDecodeInt();
            this._Wtmax = xdr.XdrDecodeInt();
            this._Wtpref = xdr.XdrDecodeInt();
            this._Wtmult = xdr.XdrDecodeInt();
            this._Dtpref = xdr.XdrDecodeInt();
            this._Maxfilesize = xdr.XdrDecodeLong();
            this._TimeDelta = new NFSTimeValue(xdr);
            this._Properties = xdr.XdrDecodeInt();
        }

        /// <summary>
        /// Gets the maximum size in bytes of a READ request.
        /// </summary>
        public int MaximumReadRequestSize
        {
            get
            { return this._Rtmax; }
        }

        /// <summary>
        /// Gets the preferred size in bytes of a READ request.
        /// </summary>
        public int PreferredReadRequestSize
        {
            get
            { return this._Rtpref; }
        }

        /// <summary>
        /// Gets the suggested multiple for the size of a READ request.
        /// </summary>
        public int ReadRequestSizeMultiplier
        {
            get
            { return this._Rtmult; }
        }

        /// <summary>
        /// Gets the maximum size in bytes of a WRITE request.
        /// </summary>
        public int MaximumWriteRequestSize
        {
            get
            { return this._Wtmax; }
        }

        /// <summary>
        /// Gets the preferred size in bytes of a WRITE request.
        /// </summary>
        public int PreferredWriteRequestSize
        {
            get
            { return this._Wtpref; }
        }

        /// <summary>
        /// Gets the suggested multiple for the size of a WRITE request.
        /// </summary>
        public int WriteRequestSizeMultiplier
        {
            get
            { return this._Wtmult; }
        }

        /// <summary>
        /// Gets the preferred size in bytes of a READDIR request.
        /// </summary>
        public int PreferredReadFolderRequestSize
        {
            get
            { return this._Dtpref; }
        }

        /// <summary>
        /// Gets the maximum file size in bytes supported by the server.
        /// </summary>
        public long MaximumFileSize
        {
            get
            { return this._Maxfilesize; }
        }

        /// <summary>
        /// Gets the server's time delta granularity.
        /// </summary>
        public NFSTimeValue DeltaTime
        {
            get
            { return this._TimeDelta; }
        }

        /// <summary>
        /// Gets the post-operation attributes of the filesystem object.
        /// </summary>
        public PostOperationAttributes Attributes
        {
            get
            { return this._ObjAttributes; }
        }

        /// <summary>
        /// Gets the filesystem properties bitmask.
        /// </summary>
        public int Properties
        {
            get
            { return this._Properties; }
        }
    }
}
