/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents successful get attribute data for NFS v3 protocol.
    /// </summary>
    public class GetAttributeAccessOK : XdrAble
    {
        private FileAttributes _ObjAttributes;

        /// <summary>
        /// Initializes a new instance of the <see cref="GetAttributeAccessOK"/> class.
        /// </summary>
        public GetAttributeAccessOK()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="GetAttributeAccessOK"/> class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public GetAttributeAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        { this._ObjAttributes.XdrEncode(xdr); }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        { this._ObjAttributes = new FileAttributes(xdr); }

        /// <summary>
        /// Gets the file attributes of the object.
        /// </summary>
        public FileAttributes Attributes
        {
            get
            { return this._ObjAttributes; }
        }
    }

    // End of GETATTR3res.cs
}