/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents failed link creation data for NFS v3 protocol.
    /// </summary>
    public class LinkAccessFAIL : XdrAble
    {
        private PostOperationAttributes _FileAttributes;
        private WritingData _LinkdirWcc;

        /// <summary>
        /// Initializes a new instance of the <see cref="LinkAccessFAIL"/> class.
        /// </summary>
        public LinkAccessFAIL()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="LinkAccessFAIL"/> class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public LinkAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._FileAttributes.XdrEncode(xdr);
            this._LinkdirWcc.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._FileAttributes = new PostOperationAttributes(xdr);
            this._LinkdirWcc = new WritingData(xdr);
        }

        /// <summary>
        /// Gets the post-operation attributes of the file.
        /// </summary>
        public PostOperationAttributes Attributes
        {
            get
            { return this._FileAttributes; }
        }

        /// <summary>
        /// Gets the weak cache consistency data for the link directory.
        /// </summary>
        public WritingData Data
        {
            get
            { return this._LinkdirWcc; }
        }
    }
}
