/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    /// <summary>
    /// Specifies the file creation mode for NFS v3 protocol operations.
    /// </summary>
    public enum MakeFileModes
    {
        /// <summary>
        /// Create the file without checking if it exists.
        /// </summary>
        UNCHECKED = 0,
        /// <summary>
        /// Create the file only if it does not exist.
        /// </summary>
        GUARDED = 1,
        /// <summary>
        /// Create the file exclusively using a verifier.
        /// </summary>
        EXCLUSIVE = 2
    }
}
