/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents successful file creation data for NFS v3 protocol.
    /// </summary>
    public class MakeFileAccessOK : XdrAble
    {
        private NFSHandle _Handle;
        private PostOperationAttributes _Attributes;
        private WritingData _DirWcc;

        /// <summary>
        /// Initializes a new instance of the <see cref="MakeFileAccessOK"/> class.
        /// </summary>
        public MakeFileAccessOK()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="MakeFileAccessOK"/> class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public MakeFileAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._Handle.XdrEncode(xdr);
            this._Attributes.XdrEncode(xdr);
            this._DirWcc.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Handle = new NFSHandle();
            this._Handle.Version = V3.RPC.NFSv3Protocol.NFS_V3;
            this._Handle.XdrDecode(xdr);
            this._Attributes = new PostOperationAttributes(xdr);
            this._DirWcc = new WritingData(xdr);
        }

        /// <summary>
        /// Gets the NFS handle of the created file.
        /// </summary>
        public NFSHandle Handle
        {
            get
            { return this._Handle; }
        }

        /// <summary>
        /// Gets the post-operation attributes of the created file.
        /// </summary>
        public PostOperationAttributes Attributes
        {
            get
            { return this._Attributes; }
        }

        /// <summary>
        /// Gets the weak cache consistency data for the parent directory.
        /// </summary>
        public WritingData Data
        {
            get
            { return this._DirWcc; }
        }
    }
}
