/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents a cookie for resuming directory read operations for NFS v3 protocol operations.
    /// </summary>
    public class NFSCookie : XdrAble
    {
        private long _Value;

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSCookie"/> class.
        /// </summary>
        public NFSCookie()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSCookie"/> class with a specified value.
        /// </summary>
        /// <param name="value">The cookie value.</param>
        public NFSCookie(long value)
        { this._Value = value; }

        /// <summary>
        /// Initializes a new instance of the <see cref="NFSCookie"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public NFSCookie(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        { xdr.XdrEncodeLong(this._Value); }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        { this._Value = xdr.XdrDecodeLong(); }

        /// <summary>
        /// Gets the cookie value for resuming directory reads.
        /// </summary>
        public long Value
        {
            get
            { return this._Value; }
        }
    }

    // End of cookie3.cs
}