/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents failed path configuration data for NFS v3 protocol.
    /// </summary>
    public class PathConfigurationAccessFAIL : XdrAble
    {
        private PostOperationAttributes _ObjAttributes;

        /// <summary>
        /// Initializes a new instance of the <see cref="PathConfigurationAccessFAIL"/> class.
        /// </summary>
        public PathConfigurationAccessFAIL()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="PathConfigurationAccessFAIL"/> class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public PathConfigurationAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        { this._ObjAttributes.XdrEncode(xdr); }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        { this._ObjAttributes = new PostOperationAttributes(xdr); }

        /// <summary>
        /// Gets the post-operation attributes of the object.
        /// </summary>
        public PostOperationAttributes Attributes
        {
            get
            { return this._ObjAttributes; }
        }
    }
}
