/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents successful path configuration data for NFS v3 protocol.
    /// </summary>
    public class PathConfigurationAccessOK : XdrAble
    {
        private PostOperationAttributes _ObjAttributes;
        private int _Linkmax;
        private int _NameMax;
        private bool _NoTrunc;
        private bool _ChownRestricted;
        private bool _CaseInsensitive;
        private bool _CasePreserving;

        /// <summary>
        /// Initializes a new instance of the <see cref="PathConfigurationAccessOK"/> class.
        /// </summary>
        public PathConfigurationAccessOK()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="PathConfigurationAccessOK"/> class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public PathConfigurationAccessOK(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._ObjAttributes.XdrEncode(xdr);
            xdr.XdrEncodeInt(this._Linkmax);
            xdr.XdrEncodeInt(this._NameMax);
            xdr.XdrEncodeBoolean(this._NoTrunc);
            xdr.XdrEncodeBoolean(this._ChownRestricted);
            xdr.XdrEncodeBoolean(this._CaseInsensitive);
            xdr.XdrEncodeBoolean(this._CasePreserving);
        }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._ObjAttributes = new PostOperationAttributes(xdr);
            this._Linkmax = xdr.XdrDecodeInt();
            this._NameMax = xdr.XdrDecodeInt();
            this._NoTrunc = xdr.XdrDecodeBoolean();
            this._ChownRestricted = xdr.XdrDecodeBoolean();
            this._CaseInsensitive = xdr.XdrDecodeBoolean();
            this._CasePreserving = xdr.XdrDecodeBoolean();
        }

        /// <summary>
        /// Gets the post-operation attributes of the object.
        /// </summary>
        public PostOperationAttributes Attributes
        {
            get
            { return this._ObjAttributes; }
        }

        /// <summary>
        /// Gets the maximum number of hard links to a file.
        /// </summary>
        public int MaximumHardLinks
        {
            get
            { return this._Linkmax; }
        }

        /// <summary>
        /// Gets the maximum length of a component of a filename.
        /// </summary>
        public int MaximumNameLength
        {
            get
            { return this._NameMax; }
        }

        /// <summary>
        /// Gets a value indicating whether the server will reject names longer than name_max with the error NAMETOOLONG.
        /// </summary>
        public bool NoTrunticate
        {
            get
            { return this._NoTrunc; }
        }

        /// <summary>
        /// Gets a value indicating whether the server will reject attempts to change file ownership.
        /// </summary>
        public bool CHOWNRestricted
        {
            get
            { return this._ChownRestricted; }
        }

        /// <summary>
        /// Gets a value indicating whether the server handles file names in a case-insensitive manner.
        /// </summary>
        public bool CaseInsensitive
        {
            get
            { return this._CaseInsensitive; }
        }

        /// <summary>
        /// Gets a value indicating whether the server preserves the case of file names.
        /// </summary>
        public bool CasePreserving
        {
            get
            { return this._CasePreserving; }
        }
    }
}
