/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents optional file attributes before an operation for NFS v3 protocol operations.
    /// </summary>
    public class PreOperationAttributes : XdrAble
    {
        private bool _AttributesFollow;
        private WritingAttributes _Attributes;

        /// <summary>
        /// Initializes a new instance of the <see cref="PreOperationAttributes"/> class.
        /// </summary>
        public PreOperationAttributes()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="PreOperationAttributes"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public PreOperationAttributes(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeBoolean(this._AttributesFollow);
            if (this._AttributesFollow)
            { this._Attributes.XdrEncode(xdr); }
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._AttributesFollow = xdr.XdrDecodeBoolean();
            if (this._AttributesFollow)
            { this._Attributes = new WritingAttributes(xdr); }
        }

        /// <summary>
        /// Gets a value indicating whether attributes are present.
        /// </summary>
        public bool AttributesExists
        {
            get
            { return this._AttributesFollow; }
        }

        /// <summary>
        /// Gets the writing attributes if present.
        /// </summary>
        public WritingAttributes Attributes
        {
            get
            { return this._Attributes; }
        }
    }

    // End of pre_op_attr.cs
}