/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents arguments for file or directory rename operations for NFS v3 protocol operations.
    /// </summary>
    public class RenameArguments : XdrAble
    {
        private ItemOperationArguments _From;
        private ItemOperationArguments _To;

        /// <summary>
        /// Initializes a new instance of the <see cref="RenameArguments"/> class.
        /// </summary>
        public RenameArguments()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="RenameArguments"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public RenameArguments(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._From.XdrEncode(xdr);
            this._To.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._From = new ItemOperationArguments(xdr);
            this._To = new ItemOperationArguments(xdr);
        }

        /// <summary>
        /// Gets or sets the source location (directory and name) to rename from.
        /// </summary>
        public ItemOperationArguments From
        {
            get
            { return this._From; }
            set
            { this._From = value; }
        }

        /// <summary>
        /// Gets or sets the target location (directory and name) to rename to.
        /// </summary>
        public ItemOperationArguments To
        {
            get
            { return this._To; }
            set
            { this._To = value; }
        }
    }

    // End of renameargs.cs
}