/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;
    using System;

    /// <summary>
    /// Represents a generic result object that can contain either a success or failure result for NFS v3 protocol operations.
    /// </summary>
    /// <typeparam name="O">The type representing a successful operation result.</typeparam>
    /// <typeparam name="F">The type representing a failed operation result.</typeparam>
    public class ResultObject<O, F> : XdrAble
    {
        private NFSStats _Status;
        private O _Resok;
        private F _Resfail;

        /// <summary>
        /// Initializes a new instance of the <see cref="ResultObject{O, F}"/> class.
        /// </summary>
        public ResultObject()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResultObject{O, F}"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public ResultObject(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt((int)this._Status);

            switch (this._Status)
            {
                case NFSStats.NFS_OK:
                    ((XdrAble)this._Resok).XdrEncode(xdr);
                    break;

                default:
                    ((XdrAble)this._Resfail).XdrEncode(xdr);
                    break;
            }
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Status = (NFSStats)xdr.XdrDecodeInt();

            switch (this._Status)
            {
                case NFSStats.NFS_OK:
                    Type OK = typeof(O);

                    this._Resok = (O)Activator.CreateInstance(OK, new object[] { xdr });
                    break;

                default:
                    Type FAIL = typeof(F);

                    this._Resfail = (F)Activator.CreateInstance(FAIL, new object[] { xdr });
                    break;
            }
        }

        /// <summary>
        /// Gets the status of the operation.
        /// </summary>
        public NFSStats Status
        {
            get
            { return this._Status; }
        }

        /// <summary>
        /// Gets the successful operation result.
        /// </summary>
        public O OK
        {
            get
            { return this._Resok; }
        }

        /// <summary>
        /// Gets the failed operation result.
        /// </summary>
        public F FAIL
        {
            get
            { return this._Resfail; }
        }
    }

    // End of FSSTAT3res.cs
}