/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents device special file information for NFS v3 protocol operations.
    /// </summary>
    public class SpecInformation : XdrAble
    {
        private int _Specdata1;
        private int _Specdata2;

        /// <summary>
        /// Initializes a new instance of the <see cref="SpecInformation"/> class.
        /// </summary>
        public SpecInformation()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="SpecInformation"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public SpecInformation(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeInt(this._Specdata1);
            xdr.XdrEncodeInt(this._Specdata2);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Specdata1 = xdr.XdrDecodeInt();
            this._Specdata2 = xdr.XdrDecodeInt();
        }

        /// <summary>
        /// Gets the major device number for special files.
        /// </summary>
        public int SpecData1
        {
            get
            { return this._Specdata1; }
        }

        /// <summary>
        /// Gets the minor device number for special files.
        /// </summary>
        public int SpecData2
        {
            get
            { return this._Specdata2; }
        }
    }

    // End of specdata3.cs
}