/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    /// <summary>
    /// Specifies the stability level for write operations for NFS v3 protocol operations.
    /// </summary>
    public enum StableHow
    {
        /// <summary>
        /// Data may be cached and not immediately written to stable storage.
        /// </summary>
        UNSTABLE = 0,
        /// <summary>
        /// Data must be committed to stable storage before the operation completes.
        /// </summary>
        DATA_SYNC = 1,
        /// <summary>
        /// Both data and metadata must be committed to stable storage before the operation completes.
        /// </summary>
        FILE_SYNC = 2
    }
}
