/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents failed symbolic link creation data for NFS v3 protocol.
    /// </summary>
    public class SymlinkAccessFAIL : XdrAble
    {
        private WritingData _DirWcc;

        /// <summary>
        /// Initializes a new instance of the <see cref="SymlinkAccessFAIL"/> class.
        /// </summary>
        public SymlinkAccessFAIL()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="SymlinkAccessFAIL"/> class from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public SymlinkAccessFAIL(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes the object to XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        { this._DirWcc.XdrEncode(xdr); }

        /// <summary>
        /// Decodes the object from XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        { this._DirWcc = new WritingData(xdr); }

        /// <summary>
        /// Gets the weak cache consistency data for the parent directory.
        /// </summary>
        public WritingData Data
        {
            get
            { return this._DirWcc; }
        }
    }
}
