/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents symbolic link data for NFS v3 protocol operations.
    /// </summary>
    public class SymlinkData : XdrAble
    {
        private MakeAttributes _SymlinkAttributes;
        private Name _SymlinkData;

        /// <summary>
        /// Initializes a new instance of the <see cref="SymlinkData"/> class.
        /// </summary>
        public SymlinkData()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="SymlinkData"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public SymlinkData(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            this._SymlinkAttributes.XdrEncode(xdr);
            this._SymlinkData.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._SymlinkAttributes = new MakeAttributes(xdr);
            this._SymlinkData = new Name(xdr);
        }

        /// <summary>
        /// Gets the attributes for the symbolic link.
        /// </summary>
        public MakeAttributes Attributes
        {
            get
            { return this._SymlinkAttributes; }
        }

        /// <summary>
        /// Gets the target path the symbolic link points to.
        /// </summary>
        public Name Name
        {
            get
            { return this._SymlinkData; }
        }
    }
}
