/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    /// <summary>
    /// Specifies how to set time attributes.
    /// </summary>
    public enum TimeHow
    {
        /// <summary>
        /// Do not change the time attribute.
        /// </summary>
        DONT_CHANGE = 0,
        /// <summary>
        /// Set the time to the server's current time.
        /// </summary>
        SET_TO_SERVER_TIME = 1,
        /// <summary>
        /// Set the time to the client-specified time.
        /// </summary>
        SET_TO_CLIENT_TIME = 2
    }
}
