/*
 * Automatically generated by jrpcgen 1.0.7 on 27/08/2010
 * jrpcgen is part of the "Remote Tea.Net" ONC/RPC package for C#
 * See http://remotetea.sourceforge.net for details
 */

namespace NFSLibrary.Protocols.V3.RPC
{
    using NFSLibrary.Protocols.Commons;
    using NFSLibrary.Rpc;

    /// <summary>
    /// Represents weak cache consistency attributes for NFS v3 protocol operations.
    /// </summary>
    public class WritingAttributes : XdrAble
    {
        private long _Size;
        private NFSTimeValue _Mtime;
        private NFSTimeValue _Ctime;

        /// <summary>
        /// Initializes a new instance of the <see cref="WritingAttributes"/> class.
        /// </summary>
        public WritingAttributes()
        { }

        /// <summary>
        /// Initializes a new instance of the <see cref="WritingAttributes"/> class by decoding from an XDR stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public WritingAttributes(XdrDecodingStream xdr)
        { XdrDecode(xdr); }

        /// <summary>
        /// Encodes this instance to an XDR encoding stream.
        /// </summary>
        /// <param name="xdr">The XDR encoding stream to write to.</param>
        public void XdrEncode(XdrEncodingStream xdr)
        {
            xdr.XdrEncodeLong(this._Size);
            this._Mtime.XdrEncode(xdr);
            this._Ctime.XdrEncode(xdr);
        }

        /// <summary>
        /// Decodes this instance from an XDR decoding stream.
        /// </summary>
        /// <param name="xdr">The XDR decoding stream to read from.</param>
        public void XdrDecode(XdrDecodingStream xdr)
        {
            this._Size = xdr.XdrDecodeLong();
            this._Mtime = new NFSTimeValue(xdr);
            this._Ctime = new NFSTimeValue(xdr);
        }

        /// <summary>
        /// Gets the file size in bytes.
        /// </summary>
        public long Size
        {
            get
            { return this._Size; }
        }

        /// <summary>
        /// Gets the last modification time.
        /// </summary>
        public NFSTimeValue ModifiedTime
        {
            get
            { return this._Mtime; }
        }

        /// <summary>
        /// Gets the creation or metadata change time.
        /// </summary>
        public NFSTimeValue CreateTime
        {
            get
            { return this._Ctime; }
        }
    }

    // End of wcc_attr.cs
}